// V9.2 sale entry + sanitized live feed. Customer PII is submitted only to protected server functions.
(function(){
  const css=document.createElement('style');css.textContent=`
  .sales-strip{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.sales-card{border:1px solid #e5e7eb;border-radius:12px;padding:12px;background:#fff}.sales-feed{max-height:260px;overflow:auto}.feed-item{padding:10px 0;border-bottom:1px solid #eee;font-size:13px}.feed-item:last-child{border-bottom:0}.leader-row{display:flex;justify-content:space-between;padding:6px 0;font-size:13px}.sale-modal{position:fixed;inset:0;z-index:120000;background:rgba(17,24,39,.78);display:none;align-items:center;justify-content:center;padding:16px}.sale-modal.show{display:flex}.sale-form{width:min(620px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:16px;padding:20px}.sale-form h2{margin-top:0}.sale-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sale-form input,.sale-form select,.sale-form textarea{width:100%;box-sizing:border-box;padding:10px;border:1px solid #d1d5db;border-radius:8px}.sale-checks{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.sale-checks label{padding:9px;background:#f8fafc;border-radius:8px;font-size:13px}.sale-actions{display:flex;gap:8px;margin-top:12px}@media(max-width:650px){.sales-strip,.sale-grid{grid-template-columns:1fr}.sale-checks{grid-template-columns:1fr}}
  `;document.head.appendChild(css);

  let providerBar=document.createElement('div');providerBar.className='sales-card';providerBar.innerHTML=`<strong>Selling for</strong><select id="sessionIsp" style="margin-top:8px;width:100%;padding:9px"><option>Quantum</option><option>Brightspeed</option><option>AT&T</option><option>Other</option></select>`;
  const fieldSelect=document.getElementById('fieldLeadSelect');fieldSelect?.parentNode?.insertBefore(providerBar,fieldSelect);
  const ispSel=document.getElementById('sessionIsp');ispSel.value=localStorage.getItem('mccoy_isp')||'Quantum';ispSel.onchange=()=>localStorage.setItem('mccoy_isp',ispSel.value);

  const social=document.createElement('div');social.className='sales-strip';social.innerHTML=`<div class="sales-card"><div style="display:flex;justify-content:space-between;gap:8px"><strong>🏆 Monthly Sales</strong><button id="salesRefreshBtn" class="assign-btn">Refresh</button></div><div id="monthlyLeaders" style="margin-top:8px">Loading…</div><button id="accountingDownloadBtn" class="assign-btn" style="display:none;margin-top:10px">Download Sales Ledger CSV</button></div><div class="sales-card"><strong>🎉 Live Wins</strong><div id="salesFeed" class="sales-feed" style="margin-top:8px">Loading…</div></div>`;
  const eff=document.getElementById('efficiencySummary');eff?.parentNode?.insertBefore(social,eff);

  const modal=document.createElement('div');modal.className='sale-modal';modal.id='saleModal';modal.innerHTML=`<div class="sale-form"><h2>Log Sale</h2><p class="muted small">Customer details are stored privately for accounting/audit. They are never posted to the social feed.</p><div class="sale-grid"><input id="saleFirst" placeholder="Customer first name *"><input id="saleLast" placeholder="Customer last name *"><input id="salePhone" placeholder="Phone"><input id="saleEmail" type="email" placeholder="Email"><input id="saleAddress" placeholder="Service address *"><select id="saleInternetProduct"><option value="Internet">Internet</option><option value="Fiber">Fiber</option><option value="Internet Air">Internet Air</option><option value="None">No Internet</option></select><input id="saleSpeed" type="number" min="0" placeholder="Internet speed Mbps (e.g. 1000)"><input id="saleMobile" type="number" min="0" max="20" value="0" placeholder="AT&T mobile lines"></div><div class="sale-checks"><label><input id="saleDirectv" type="checkbox"> DIRECTV</label><label><input id="saleVivint" type="checkbox"> Vivint</label><label><input id="saleConfirm" type="checkbox"> Information reviewed</label></div><textarea id="saleNotes" rows="3" placeholder="Internal notes (optional)"></textarea><div id="saleMsg" class="muted small" style="margin-top:8px"></div><div class="sale-actions"><button id="submitSaleBtn" class="success">SAVE SALE</button><button id="cancelSaleBtn" class="assign-btn">Cancel</button></div></div>`;document.body.appendChild(modal);

  let pendingSaleBtn=null;
  document.addEventListener('click',(e)=>{const b=e.target?.closest?.('[data-disp="Sale"]');if(!b||window.MCCOY_SALE_CONFIRMED)return;e.preventDefault();e.stopImmediatePropagation();if(!state.session){alert('Start Knocking first.');return;}if(!state.activeDoorVisit){alert('Tap PHYSICALLY KNOCKED first.');return;}pendingSaleBtn=b;const lead=state.activeDoorVisit.lead;document.getElementById('saleAddress').value=lead?.address||'';document.getElementById('saleMsg').textContent='';modal.classList.add('show');},true);
  document.getElementById('cancelSaleBtn').onclick=()=>{pendingSaleBtn=null;modal.classList.remove('show');};

  async function submitSale(){
    const first=document.getElementById('saleFirst').value.trim(),last=document.getElementById('saleLast').value.trim(),address=document.getElementById('saleAddress').value.trim();if(!first||!last||!address){document.getElementById('saleMsg').textContent='First name, last name, and service address are required.';return;}if(!document.getElementById('saleConfirm').checked){document.getElementById('saleMsg').textContent='Review the information and check Information reviewed.';return;}
    const btn=document.getElementById('submitSaleBtn');btn.disabled=true;btn.textContent='SAVING…';const lead=state.activeDoorVisit?.lead;
    const body={session_id:telemetrySessionId,lead_label:lead?.address||null,customer_first_name:first,customer_last_name:last,customer_phone:document.getElementById('salePhone').value.trim()||null,customer_email:document.getElementById('saleEmail').value.trim()||null,service_address:address,isp:ispSel.value,internet_product:document.getElementById('saleInternetProduct').value,internet_speed_mbps:Number(document.getElementById('saleSpeed').value||0)||null,att_mobile_lines:Number(document.getElementById('saleMobile').value||0),directv:document.getElementById('saleDirectv').checked,vivint:document.getElementById('saleVivint').checked,notes:document.getElementById('saleNotes').value.trim()||null};
    const {data,error}=await sb.functions.invoke('sale-submit',{body});btn.disabled=false;btn.textContent='SAVE SALE';if(error||!data?.ok){console.error(error,data);document.getElementById('saleMsg').textContent='Sale could not be saved. Check connection and try again.';return;}
    modal.classList.remove('show');['saleFirst','saleLast','salePhone','saleEmail','saleSpeed','saleNotes'].forEach(id=>document.getElementById(id).value='');document.getElementById('saleMobile').value='0';document.getElementById('saleDirectv').checked=false;document.getElementById('saleVivint').checked=false;document.getElementById('saleConfirm').checked=false;
    const b=pendingSaleBtn;pendingSaleBtn=null;window.MCCOY_SALE_CONFIRMED=true;b?.click();window.MCCOY_SALE_CONFIRMED=false;await loadFeed();
  }
  document.getElementById('submitSaleBtn').onclick=submitSale;

  async function loadFeed(){
    if(!window.MCCOY_ACCESS?.user)return;const start=new Date();start.setDate(1);start.setHours(0,0,0,0);const {data,error}=await sb.from('sales_feed').select('created_at,rep_user_id,rep_name,isp,directv,att_mobile_lines,vivint,message').gte('created_at',start.toISOString()).order('created_at',{ascending:false}).limit(100);if(error){console.error(error);return;}const rows=data||[];document.getElementById('salesFeed').innerHTML=rows.slice(0,20).map(r=>`<div class="feed-item"><strong>${r.message}</strong><div class="muted small">${new Date(r.created_at).toLocaleString()}</div></div>`).join('')||'<div class="muted small">No sales posted this month yet.</div>';
    const m=new Map();for(const r of rows){const x=m.get(r.rep_user_id)||{name:r.rep_name,sales:0,mobile:0,directv:0,vivint:0};x.sales++;x.mobile+=r.att_mobile_lines||0;x.directv+=r.directv?1:0;x.vivint+=r.vivint?1:0;m.set(r.rep_user_id,x);}const leaders=[...m.values()].sort((a,b)=>b.sales-a.sales);document.getElementById('monthlyLeaders').innerHTML=leaders.slice(0,10).map((x,i)=>`<div class="leader-row"><span>${i+1}. ${x.name}</span><strong>${x.sales} sale${x.sales===1?'':'s'}</strong></div><div class="muted small">${x.mobile} mobile lines · ${x.directv} DIRECTV · ${x.vivint} Vivint</div>`).join('')||'<div class="muted small">No monthly totals yet.</div>';
  }
  document.getElementById('salesRefreshBtn').onclick=loadFeed;

  async function downloadLedger(){const {data:{session}}=await sb.auth.getSession();if(!session)return;const resp=await fetch(SUPABASE_URL+'/functions/v1/accounting-sales?format=csv',{headers:{Authorization:'Bearer '+session.access_token,apikey:SUPABASE_PUBLISHABLE_KEY}});if(!resp.ok){alert('Accounting export failed.');return;}const blob=await resp.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mccoy-sales-ledger.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  document.getElementById('accountingDownloadBtn').onclick=downloadLedger;

  const authPoll=setInterval(()=>{const a=window.MCCOY_ACCESS?.access;if(!a)return;clearInterval(authPoll);if(a.role==='admin')document.getElementById('accountingDownloadBtn').style.display='inline-block';loadFeed();sb.channel('mccoy-sales-feed').on('postgres_changes',{event:'INSERT',schema:'public',table:'sales_feed'},()=>loadFeed()).subscribe();},400);
})();
