// McCoy Field Coach V9.2 authentication and self-service onboarding.
window.MCCOY_ACCESS={user:null,access:null};
(function(){
 const css=document.createElement('style');css.textContent=`
 #authGate{position:fixed;inset:0;z-index:99999;background:#f4f6f8;display:flex;align-items:center;justify-content:center;padding:18px}#authGate.hidden{display:none!important}#authGate.auth-checking .auth-card{visibility:hidden}
 .auth-card{width:min(460px,100%);background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:24px;box-shadow:0 14px 44px rgba(0,0,0,.12)}.auth-card h2{margin:0 0 6px}.auth-card p{color:#6b7280;font-size:13px;line-height:1.45}.auth-card input,.auth-card select{box-sizing:border-box;width:100%;padding:12px;margin:6px 0;border:1px solid #d1d5db;border-radius:10px;background:#fff;font-size:16px}.auth-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.auth-msg{font-size:12px;margin-top:10px;min-height:18px}.auth-step{display:none}.auth-step.active{display:block}.auth-link{border:0;background:none;text-decoration:underline;color:#374151;cursor:pointer;padding:8px 0}.user-strip{position:fixed;right:12px;bottom:12px;z-index:1000;background:#111827;color:#fff;border-radius:999px;padding:7px 10px;font-size:11px;display:flex;gap:8px;align-items:center}.user-strip button{border:0;border-radius:999px;padding:4px 7px;cursor:pointer}
 #accessAdminBtn{position:fixed;right:14px;bottom:14px;z-index:2600;display:none;border:0;border-radius:999px;padding:9px 13px;background:#111827;color:#fff;font-size:12px;cursor:pointer}#accessAdminPanel{position:fixed;inset:0;z-index:140000;background:rgba(17,24,39,.78);display:none;align-items:center;justify-content:center;padding:16px}#accessAdminPanel.show{display:flex}.access-card{width:min(780px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:16px;padding:20px}.access-row{border-top:1px solid #eef0f2;padding:12px 0}.access-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:8px}.access-actions{display:flex;gap:8px;margin-top:8px}
 body.blind-tester .sidebar{display:flex!important}body.blind-tester .sidebar .nav-btn[data-view="teams"],body.blind-tester .sidebar .nav-btn[data-view="settings"]{display:none!important}body.blind-tester #teams,body.blind-tester #settings{display:none!important}body.blind-tester #dashboard > :not(#dashboardRepRankings){display:none!important}body.blind-tester #dashboard.active,body.blind-tester #field.active,body.blind-tester #leads.active,body.blind-tester #sales.active{display:block!important}body.blind-tester #field{padding:16px!important}body.blind-tester .topbar .muted,body.blind-tester #modeBadge{display:none!important}body.blind-tester .topbar{height:68px;padding:0 16px}body.blind-tester #pageTitle{font-size:20px}body.blind-tester #geoBox,body.blind-tester #gpsQualityBox,body.blind-tester #doorPresenceBox,body.blind-tester #telemetryStatus{display:none!important}body.blind-tester .field-controls>.geo-box:not(#telemetryStatus){display:none!important}body.blind-tester .grid-2>.card:nth-child(2){display:none!important}body.blind-tester .calibration-panel{display:none!important}body.blind-tester #doorVisitStatus,body.blind-tester .door-visit-panel .muted,body.blind-tester .door-timer{display:none!important}body.blind-tester #activityLog,body.blind-tester #efficiencySummary{display:none!important}body.blind-tester #arriveDoorBtn{margin:8px 0 14px}body.blind-tester .card-head p{display:none!important}body.blind-tester .card-head h2{font-size:15px}body.blind-tester .disposition-grid{margin-top:8px}
 @media(max-width:600px){.auth-actions{grid-template-columns:1fr}.access-grid{grid-template-columns:1fr}.user-strip{max-width:90vw}}
 `;document.head.appendChild(css);

 const gate=document.createElement('div');gate.id='authGate';gate.className='auth-checking';gate.innerHTML=`<div class="auth-card">
  <div id="loginStep" class="auth-step active"><h2>McCoy Field Coach V9.2</h2><p>Sign in to continue.</p><input id="authEmail" type="email" autocomplete="email" placeholder="Email address"><input id="authPassword" type="password" autocomplete="current-password" placeholder="Password"><div class="auth-actions"><button id="signInBtn" class="primary">SIGN IN</button><button id="showSignupBtn" class="assign-btn">CREATE ACCOUNT</button></div><button id="showResetBtn" class="auth-link">Forgot password?</button><div id="authMsg" class="auth-msg"></div></div>
  <div id="signupStep" class="auth-step"><h2>Create McCoy Field Coach Account</h2><p>Create your login, verify your email if prompted, then request access.</p><input id="signupName" autocomplete="name" placeholder="Full name"><input id="signupEmail" type="email" autocomplete="email" placeholder="Email address"><input id="signupPassword" type="password" autocomplete="new-password" placeholder="Password (8+ characters)"><select id="signupTeam"><option value="">Select team (optional)</option><option>Pacific Northwest</option><option>North Carolina</option></select><button id="createAccountBtn" class="primary" style="width:100%;margin-top:8px">CREATE ACCOUNT</button><button id="backLoginBtn" class="auth-link">Back to sign in</button><div id="signupMsg" class="auth-msg"></div></div>
  <div id="resetStep" class="auth-step"><h2>Reset your password</h2><p>Enter your email and we’ll send a secure password-reset link.</p><input id="resetEmail" type="email" autocomplete="email" placeholder="Email address"><button id="sendResetBtn" class="primary" style="width:100%;margin-top:8px">SEND RESET LINK</button><button id="showRecoveryLinkHelpBtn" class="auth-link" style="display:block">Reset link not working?</button><div id="recoveryLinkHelp" hidden><p>Copy the complete reset link from your newest email, or the complete address from a failed localhost page, and paste it below. Do not share this link with anyone.</p><textarea id="recoveryLinkInput" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Paste your complete password-reset link here" style="box-sizing:border-box;width:100%;min-height:84px;padding:10px;border:1px solid #d1d5db;border-radius:10px;resize:vertical"></textarea><button id="useRecoveryLinkBtn" class="assign-btn" style="width:100%;margin-top:8px">VERIFY RESET LINK</button></div><button id="backResetLoginBtn" class="auth-link">Back to sign in</button><div id="resetMsg" class="auth-msg"></div></div><div id="recoveryStep" class="auth-step"><h2>Choose a new password</h2><p>Set a new password for your McCoy Field Coach account.</p><input id="newRecoveryPassword" type="password" autocomplete="new-password" placeholder="New password (8+ characters)"><input id="confirmRecoveryPassword" type="password" autocomplete="new-password" placeholder="Confirm new password"><button id="updateRecoveryPasswordBtn" class="primary" style="width:100%;margin-top:8px">UPDATE PASSWORD</button><div id="recoveryMsg" class="auth-msg"></div></div><div id="requestStep" class="auth-step"><h2>Request Access</h2><p>Complete your access request for McCoy Field Coach V9.2.</p><input id="requestName" autocomplete="name" placeholder="Full name"><select id="requestTeam"><option value="">Select team (optional)</option><option>Pacific Northwest</option><option>North Carolina</option></select><button id="requestAccessBtn" class="primary" style="width:100%;margin-top:8px">REQUEST ACCESS</button><button id="requestSignOutBtn" class="auth-link">Sign out</button><div id="requestMsg" class="auth-msg"></div></div>
  <div id="pendingStep" class="auth-step"><h2>Access Request Pending</h2><p>Your account is ready. Access will become available after approval.</p><button id="checkApprovalBtn" class="primary" style="width:100%">CHECK APPROVAL</button><button id="pendingSignOutBtn" class="auth-link">Sign out</button><div id="pendingMsg" class="auth-msg"></div></div>
 </div>`;document.body.appendChild(gate);
 function step(id){document.querySelectorAll('#authGate .auth-step').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');}
 function setMsg(id,text,ok=false){const el=document.getElementById(id);if(el){el.textContent=text;el.style.color=ok?'#166534':'#991b1b';}}
 const RECOVERY_DESTINATION='https://mccoy-field-test.vercel.app/';
 const RECOVERY_FLAG='mccoy_password_recovery_active';
 const incomingHash=new URLSearchParams((location.hash||'').replace(/^#/,''));
 const incomingSearch=new URLSearchParams(location.search||'');
 let recoveryMode=incomingHash.get('type')==='recovery'||incomingSearch.get('type')==='recovery';
 try{recoveryMode=recoveryMode||window.sessionStorage?.getItem(RECOVERY_FLAG)==='1';}catch(_error){}
 function setRecoveryMode(active){recoveryMode=Boolean(active);try{if(recoveryMode)window.sessionStorage?.setItem(RECOVERY_FLAG,'1');else window.sessionStorage?.removeItem(RECOVERY_FLAG);}catch(_error){}}
 function showRecoveryForm(message='Choose and confirm a new password.'){setRecoveryMode(true);gate.classList.remove('hidden','auth-checking');step('recoveryStep');setMsg('recoveryMsg',message,true);}
 async function verifyRecoveryLink(){
   const input=document.getElementById('recoveryLinkInput');const raw=input?.value.trim()||'';
   if(!raw){setMsg('resetMsg','Paste the full reset link from your newest email.');return;}
   let url;try{url=new URL(raw);}catch(_error){setMsg('resetMsg','Paste a complete password-reset URL, including https:// or http://localhost.');return;}
   const trustedHosts=['mccoy-field-test.vercel.app','athxxrfqxwlfnuvbqadp.supabase.co','localhost','127.0.0.1'];
   if(!trustedHosts.includes(url.hostname.toLowerCase())){setMsg('resetMsg','This reset link does not belong to McCoy Platform.');return;}
   const hash=new URLSearchParams(url.hash.replace(/^#/,''));const query=url.searchParams;
   const type=hash.get('type')||query.get('type');
   if(type&&type!=='recovery'){setMsg('resetMsg','This link is not a password-reset link.');return;}
   if(hash.get('error')||query.get('error')){setMsg('resetMsg','That reset link has expired or was already used. Request a new link and copy it without opening the old one.');return;}
   const accessToken=hash.get('access_token')||query.get('access_token');const refreshToken=hash.get('refresh_token')||query.get('refresh_token');
   const tokenHash=query.get('token_hash')||query.get('token')||hash.get('token_hash');const authCode=query.get('code')||hash.get('code');
   if(!(accessToken&&refreshToken)&&!tokenHash&&!authCode){setMsg('resetMsg','This link does not contain a usable recovery token. Request a new reset link.');return;}
   setMsg('resetMsg','Verifying your secure reset link...',true);setRecoveryMode(true);
   try{
     let result;
     if(accessToken&&refreshToken)result=await sb.auth.setSession({access_token:accessToken,refresh_token:refreshToken});
     else if(tokenHash)result=await sb.auth.verifyOtp({token_hash:tokenHash,type:'recovery'});
     else result=await sb.auth.exchangeCodeForSession(authCode);
     if(result?.error)throw result.error;
     if(input)input.value='';showRecoveryForm('Reset link verified. Choose and confirm your new password.');
   }catch(error){setRecoveryMode(false);const expired=/expired|invalid|not found|already|otp/i.test(error?.message||'');setMsg('resetMsg',expired?'That reset link has expired or was already used. Request a new link, then copy the newest email link without opening it.':error?.message||'Unable to verify this reset link.');}
 }
 async function onboarding(action,payload={}){const {data,error}=await sb.functions.invoke('rep-onboarding',{body:{action,...payload}});if(error)throw error;return data;}
 function applyMode(user,access){window.MCCOY_ACCESS={user,access};window.dispatchEvent(new Event('mccoy-access-ready'));gate.classList.remove('auth-checking');gate.classList.add('hidden');document.body.classList.toggle('blind-tester',access.role!=='admin');if(access.role!=='admin'){if(document.getElementById('pageTitle'))document.getElementById('pageTitle').textContent='McCoy Field Coach V9.2';if(document.getElementById('arriveDoorBtn'))document.getElementById('arriveDoorBtn').textContent='PHYSICALLY KNOCKED';document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('field')?.classList.add('active');}else if(document.getElementById('arriveDoorBtn'))document.getElementById('arriveDoorBtn').textContent='ARRIVE AT DOOR / START VISIT';let strip=document.getElementById('userStrip');if(!strip){strip=document.createElement('div');strip.id='userStrip';strip.className='user-strip';document.body.appendChild(strip);}strip.innerHTML=`<span>${access.display_name||user.email} · ${access.role}</span><button id="signOutBtn">Sign out</button>`;document.getElementById('signOutBtn').onclick=async()=>{await sb.auth.signOut();location.reload();};if(access.role==='admin')setupAdminApprovals();}
 async function routeAuthenticated(){
   if(recoveryMode){gate.classList.remove('hidden','auth-checking');step('recoveryStep');return true;}
   try{
     const {data:{user}}=await sb.auth.getUser();if(!user){gate.classList.remove('hidden','auth-checking');step('loginStep');return false;}
     const d=await onboarding('status');if(d?.access?.active){applyMode(user,d.access);return true;}
     window.MCCOY_ACCESS={user,access:null};gate.classList.remove('hidden','auth-checking');
     if(d?.request?.status==='pending'){step('pendingStep');setMsg('pendingMsg','Request submitted. You can leave this page and return later.',true);}
     else if(d?.request?.status==='rejected'){step('requestStep');setMsg('requestMsg','Your prior request was not approved. Contact your McCoy administrator.');}
     else{step('requestStep');const n=user.user_metadata?.display_name||user.user_metadata?.full_name||'';if(n)document.getElementById('requestName').value=n;}
     return false;
   }catch(e){console.error(e);gate.classList.remove('hidden','auth-checking');step('loginStep');setMsg('authMsg','Unable to check access right now.');return false;}
 }
 document.getElementById('showSignupBtn').onclick=()=>{document.getElementById('signupEmail').value=document.getElementById('authEmail').value;step('signupStep');};document.getElementById('backLoginBtn').onclick=()=>step('loginStep');document.getElementById('showResetBtn').onclick=()=>{document.getElementById('resetEmail').value=document.getElementById('authEmail').value;step('resetStep');};document.getElementById('backResetLoginBtn').onclick=()=>{setRecoveryMode(false);step('loginStep');};document.getElementById('showRecoveryLinkHelpBtn').onclick=()=>{const help=document.getElementById('recoveryLinkHelp');help.hidden=!help.hidden;if(!help.hidden)document.getElementById('recoveryLinkInput')?.focus();};document.getElementById('useRecoveryLinkBtn').onclick=verifyRecoveryLink;document.getElementById('sendResetBtn').onclick=async()=>{const email=document.getElementById('resetEmail').value.trim().toLowerCase();if(!email){setMsg('resetMsg','Enter your email address.');return;}setRecoveryMode(false);setMsg('resetMsg','Sending a new secure reset link...',true);const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:RECOVERY_DESTINATION});if(error){setMsg('resetMsg',error.message);return;}setMsg('resetMsg','If an account exists for this email, a new reset link has been sent. Use only the newest email.',true);};document.getElementById('updateRecoveryPasswordBtn').onclick=async()=>{const password=document.getElementById('newRecoveryPassword').value,confirm=document.getElementById('confirmRecoveryPassword').value;if(password.length<8){setMsg('recoveryMsg','Use a password at least 8 characters long.');return;}if(password!==confirm){setMsg('recoveryMsg','Passwords do not match.');return;}setMsg('recoveryMsg','Updating password...',true);const {error}=await sb.auth.updateUser({password});if(error){setMsg('recoveryMsg',error.message);return;}setRecoveryMode(false);setMsg('recoveryMsg','Password updated. You can now sign in with your new password.',true);setTimeout(async()=>{await sb.auth.signOut();history.replaceState(history.state,'',location.pathname);location.reload();},1200);};
 document.getElementById('signInBtn').onclick=async()=>{setMsg('authMsg','Signing in...',true);const email=document.getElementById('authEmail').value.trim().toLowerCase(),password=document.getElementById('authPassword').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error){setMsg('authMsg',error.message);return;}await routeAuthenticated();};
 document.getElementById('createAccountBtn').onclick=async()=>{const name=document.getElementById('signupName').value.trim(),email=document.getElementById('signupEmail').value.trim().toLowerCase(),password=document.getElementById('signupPassword').value,team=document.getElementById('signupTeam').value;if(name.length<2){setMsg('signupMsg','Enter your full name.');return;}if(password.length<8){setMsg('signupMsg','Use a password at least 8 characters long.');return;}setMsg('signupMsg','Creating account...',true);const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name,requested_team:team},emailRedirectTo:location.origin+location.pathname}});if(error){setMsg('signupMsg',error.message);return;}if(data.session){document.getElementById('requestName').value=name;document.getElementById('requestTeam').value=team;await routeAuthenticated();}else setMsg('signupMsg','Account created. Check your email and confirm your address, then return here and sign in.',true);};
 document.getElementById('requestAccessBtn').onclick=async()=>{const name=document.getElementById('requestName').value.trim(),team=document.getElementById('requestTeam').value;if(name.length<2){setMsg('requestMsg','Enter your full name.');return;}setMsg('requestMsg','Submitting request...',true);try{const d=await onboarding('request_access',{display_name:name,requested_team:team});if(d?.access?.active){await routeAuthenticated();return;}step('pendingStep');setMsg('pendingMsg','Access request sent.',true);}catch(e){console.error(e);setMsg('requestMsg','Unable to submit access request.');}};
 document.getElementById('checkApprovalBtn').onclick=async()=>{setMsg('pendingMsg','Checking...',true);await routeAuthenticated();};for(const id of ['requestSignOutBtn','pendingSignOutBtn'])document.getElementById(id).onclick=async()=>{await sb.auth.signOut();location.reload();};

 function setupAdminApprovals(){let btn=document.getElementById('accessAdminBtn');if(btn)return;btn=document.createElement('button');btn.id='accessAdminBtn';btn.textContent='Access Requests';btn.style.display='block';document.body.appendChild(btn);const panel=document.createElement('div');panel.id='accessAdminPanel';panel.innerHTML='<div class="access-card"><h2>Rep Access Requests</h2><p class="muted">Approve accounts and assign team/manager.</p><div id="accessRequestsBody">Loading…</div><div style="text-align:right;margin-top:12px"><button id="accessPanelClose" class="assign-btn">Close</button></div></div>';document.body.appendChild(panel);document.getElementById('accessPanelClose').onclick=()=>panel.classList.remove('show');btn.onclick=async()=>{panel.classList.add('show');await loadRequests();};}
 async function loadRequests(){const root=document.getElementById('accessRequestsBody');root.textContent='Loading…';try{const d=await onboarding('list_pending');const reqs=d?.requests||[],mgrs=d?.managers||[];if(!reqs.length){root.innerHTML='<p class="muted">No pending access requests.</p>';return;}root.innerHTML=reqs.map((r,i)=>`<div class="access-row"><strong>${esc(r.display_name||r.email)}</strong><div class="muted small">${esc(r.email)} · requested ${esc(r.requested_team||'no team')}</div><div class="access-grid"><select id="arRole${i}"><option value="rep">Rep</option><option value="manager">Manager</option><option value="trainer">Trainer</option></select><select id="arTeam${i}"><option value="">No team</option><option ${r.requested_team==='Pacific Northwest'?'selected':''}>Pacific Northwest</option><option ${r.requested_team==='North Carolina'?'selected':''}>North Carolina</option></select><select id="arMgr${i}"><option value="">No Manager / Trainer</option>${mgrs.map(m=>`<option value="${esc(m.email)}">${esc(m.display_name||m.email)} (${esc(m.role==='admin'?'Admin':m.role==='trainer'?'Trainer':'Manager')})</option>`).join('')}</select></div><div class="access-actions"><button class="primary" id="arApprove${i}">Approve</button><button class="assign-btn" id="arReject${i}">Reject</button></div></div>`).join('');reqs.forEach((r,i)=>{document.getElementById('arApprove'+i).onclick=async()=>{await onboarding('approve',{request_id:r.id,role:document.getElementById('arRole'+i).value,team_name:document.getElementById('arTeam'+i).value,assigned_manager_email:document.getElementById('arMgr'+i).value});await loadRequests();};document.getElementById('arReject'+i).onclick=async()=>{await onboarding('reject',{request_id:r.id});await loadRequests();};});}catch(e){console.error(e);root.textContent='Unable to load access requests.';}}
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

 saveTestSessionStart=async function(startedAt){const {data:{user},error:userError}=await sb.auth.getUser();if(userError||!user||!window.MCCOY_ACCESS.access)return false;telemetrySessionId=uuidv4();const {error}=await sb.from('test_sessions').insert({id:telemetrySessionId,tester_name:window.MCCOY_ACCESS.access.display_name||user.email,tester_user_id:user.id,tester_email:user.email,started_at:new Date(startedAt).toISOString(),user_agent:navigator.userAgent,app_version:'9.2-auto-stop'});if(error){console.error('Telemetry session insert failed',error);telemetrySessionId=null;return false;}return true;};
 sb.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'||(recoveryMode&&event==='SIGNED_IN')){showRecoveryForm();return;}if(event==='SIGNED_OUT')setRecoveryMode(false);setTimeout(routeAuthenticated,0);});
 const initialRecoveryError=incomingHash.get('error_code')||incomingHash.get('error')||incomingSearch.get('error_code')||incomingSearch.get('error');
 if(initialRecoveryError){setRecoveryMode(false);gate.classList.remove('hidden','auth-checking');step('resetStep');setMsg('resetMsg','That password-reset link has expired or was already used. Request a new reset link.');}
 else if(recoveryMode)showRecoveryForm();
 else routeAuthenticated();
})();
