const SUPABASE_URL='https://athxxrfqxwlfnuvbqadp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_UB8C4-fhWPLpba6xta6EKg_hBtZC2iT';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const authMsg=document.getElementById('authMsg'),uploadMsg=document.getElementById('uploadMsg'),signInBtn=document.getElementById('signIn'),uploadBtn=document.getElementById('upload'),importType=document.getElementById('importType'),fileInput=document.getElementById('file');
function setAuth(message,ok=false){authMsg.textContent=message;authMsg.style.color=ok?'#166534':'#991b1b';}
async function verifyAdmin(){const {data:{user},error:userError}=await sb.auth.getUser();if(userError||!user?.email)throw new Error(userError?.message||'No signed-in McCoy user found.');const {data:access,error:accessError}=await sb.from('app_user_access').select('role,active,display_name').eq('email',user.email.toLowerCase()).maybeSingle();if(accessError)throw accessError;if(!access?.active||access.role!=='admin')throw new Error('Admin access required.');return {user,access};}
async function restoreSession(){try{const {data:{session}}=await sb.auth.getSession();if(!session)return;const {access}=await verifyAdmin();setAuth(`Already signed in as ${access.display_name||session.user.email}.`,true);signInBtn.textContent='SIGNED IN';}catch(e){await sb.auth.signOut().catch(()=>{});}}
signInBtn.addEventListener('click',async()=>{try{signInBtn.disabled=true;setAuth('Signing in…',true);const email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value;if(!email||!password)throw new Error('Enter your McCoy Admin email and password.');const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;const {access}=await verifyAdmin();setAuth(`Admin signed in as ${access.display_name||email}.`,true);signInBtn.textContent='SIGNED IN';}catch(e){await sb.auth.signOut().catch(()=>{});setAuth(e?.message||String(e));signInBtn.textContent='SIGN IN';}finally{signInBtn.disabled=false;}});
function refreshImportHelp(){document.getElementById('spotioHelp').style.display=importType.value==='spotio_json'?'block':'none';document.getElementById('csvHelp').style.display=importType.value==='csv'?'block':'none';}
importType.addEventListener('change',refreshImportHelp);
function detectImportType(file,text=''){const name=String(file?.name||'').toLowerCase();const mime=String(file?.type||'').toLowerCase();if(name.endsWith('.csv')||mime.includes('csv'))return 'csv';if(name.endsWith('.json')||mime.includes('json'))return 'spotio_json';const sample=String(text||'').trimStart();if(sample.startsWith('{')||sample.startsWith('['))return 'spotio_json';if(sample.includes(',')&&(sample.includes('\n')||sample.includes('\r')))return 'csv';return importType.value;}
fileInput.addEventListener('change',()=>{const f=fileInput.files?.[0];if(!f)return;const detected=detectImportType(f);if(detected!==importType.value){importType.value=detected;refreshImportHelp();uploadMsg.style.color='#166534';uploadMsg.textContent=detected==='csv'?'CSV detected automatically. Ready to upload.':'JSON capture detected automatically. Ready to upload.';}});
function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){field+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);field='';if(row.some(v=>v!==''))rows.push(row);row=[];}else field+=c;}row.push(field);if(row.some(v=>v!==''))rows.push(row);if(!rows.length)return {headers:[],rows:[]};const headers=rows[0].map((h,i)=>(h||`column_${i+1}`).trim().replace(/^\uFEFF/,''));return {headers,rows:rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))};}
async function callImport(session,body){const r=await fetch(SUPABASE_URL+'/functions/v1/spotio-import',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||`Upload failed (${r.status})`);return d;}
uploadBtn.addEventListener('click',async()=>{try{uploadBtn.disabled=true;const f=fileInput.files[0];if(!f)throw new Error('Choose a JSON or CSV file first.');uploadMsg.style.color='#374151';uploadMsg.textContent='Checking Admin session…';await verifyAdmin();const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Sign in as Admin first.');uploadMsg.textContent='Reading file…';const fileText=await f.text();const type=detectImportType(f,fileText);if(type!==importType.value){importType.value=type;refreshImportHelp();}let records=[],meta={};if(type==='csv'){const parsed=parseCSV(fileText);if(!parsed.headers.length)throw new Error('CSV has no header row.');records=parsed.rows;meta={headers:parsed.headers,source:'csv'};}else{let raw;try{raw=JSON.parse(fileText);}catch(e){if(detectImportType(f,fileText)==='csv')throw new Error('This is a CSV file. McCoy detected it as CSV; please try the upload again.');throw new Error('The selected JSON file is not valid JSON.');}const captures=Array.isArray(raw?.captures)?raw.captures:[];const domLeads=Array.isArray(raw?.dom_leads)?raw.dom_leads:[];if(domLeads.length){records=domLeads;meta={source:'spotio_dom_capture',capture_mode:'dom_rows',source_origin:raw.source_origin||null,started_at:raw.started_at||null,finished_at:raw.finished_at||null,summary:raw.summary||null,api_capture_count:captures.length,dom_row_count:domLeads.length};}else if(captures.length){records=captures;meta={source:'spotio_browser_capture',capture_mode:'api_responses',source_origin:raw.source_origin||null,started_at:raw.started_at||null,finished_at:raw.finished_at||null,summary:raw.summary||null};}else if(Array.isArray(raw)){records=raw;meta={source:'spotio_legacy_array',capture_mode:'legacy'};}if(!records.length)throw new Error('No SPOTIO lead rows or captured responses found in this JSON file.');}
const init=await callImport(session,{action:'init',source_filename:f.name,source_type:type,captured_at:new Date().toISOString(),record_count:records.length,metadata:meta});const batchId=init.batch.id;const isDom=type==='spotio_json'&&meta.capture_mode==='dom_rows';const CHUNK=type==='csv'||isDom?250:20;const total=Math.ceil(records.length/CHUNK);for(let i=0;i<total;i++){uploadMsg.textContent=`Uploading chunk ${i+1} of ${total}…`;await callImport(session,{action:'chunk',batch_id:batchId,chunk_index:i,records:records.slice(i*CHUNK,(i+1)*CHUNK)});}uploadMsg.textContent='Finalizing upload…';await callImport(session,{action:'finalize',batch_id:batchId});uploadMsg.textContent=type==='csv'?'Normalizing CSV leads into the live Lead Pool…':'Verifying and normalizing SPOTIO leads…';const n=await callImport(session,{action:'normalize',batch_id:batchId});if(n.complete){uploadMsg.style.color='#166534';uploadMsg.textContent=type==='csv'?`CSV import COMPLETE. ${n.unique_imported} leads added to the live Lead Pool. Batch ${batchId}.`:`SPOTIO import COMPLETE. ${n.unique_imported} / ${n.expected} leads verified. Batch ${batchId}.`;}else{uploadMsg.style.color='#991b1b';uploadMsg.textContent=`Import INCOMPLETE. ${n.unique_imported} / ${n.expected||'?'} leads normalized; ${n.missing??'?'} missing. Batch ${batchId}.`;}}catch(e){uploadMsg.style.color='#991b1b';uploadMsg.textContent=e?.message||String(e);}finally{uploadBtn.disabled=false;}});
restoreSession();
