import { createClient } from 'npm:@supabase/supabase-js@2.95.0'
import { corsHeaders } from 'npm:@supabase/supabase-js@2.95.0/cors'

type E = {event_type:string;lead_label:string|null;disposition:string|null;event_time:string;latitude:number|null;longitude:number|null;accuracy_meters:number|null;gps_fix_age_ms:number|null;dwell_ms:number|null;lead_latitude:number|null;lead_longitude:number|null;distance_to_lead_meters:number|null;payload:any}
const ENGINE='1.0-server';
const CFG={verifiedAcc:15,verifiedAge:5000,strongProperty:30,probableProperty:60,doorZone:30,stopRadius:8,stopMinMs:15000,offRoute:75,longIdleMs:300000,crowdFt:5,comfortableFt:8,walkMin:0.5,walkMax:2.4};
const R=6371000,toRad=(x:number)=>x*Math.PI/180;
function dist(a:any,b:any){if(!a||!b||a.latitude==null||b.latitude==null)return null;const dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
const verified=(e:E)=>e.latitude!=null&&e.longitude!=null&&(e.accuracy_meters??999)<=CFG.verifiedAcc&&(e.gps_fix_age_ms??0)<=CFG.verifiedAge;
function median(v:number[]){if(!v.length)return null;const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function pointMedian(es:E[]){const v=es.filter(verified);const lat=median(v.map(x=>x.latitude!)),lng=median(v.map(x=>x.longitude!));return lat==null||lng==null?null:{latitude:lat,longitude:lng,count:v.length};}
function propertyStatus(e:E){if(!verified(e))return 'Unknown';let d=e.distance_to_lead_meters;if(d==null&&e.lead_latitude!=null){d=dist(e,{latitude:e.lead_latitude,longitude:e.lead_longitude});}if(d==null)return 'Unknown';return d<=CFG.strongProperty?'On Property / Strong Match':d<=CFG.probableProperty?'Near Property / Probable Match':'Outside Property Area';}
function comfort(e:E,door:any){if(!door||!verified(e))return {status:'Unknown',confidence:'Low'};const m=dist(e,door)!;const ft=m*3.28084,acc=(e.accuracy_meters??999)*3.28084,low=Math.max(0,ft-acc),high=ft+acc;let status='Uncertain',confidence='Medium';if(high<CFG.crowdFt){status='Likely Too Close';confidence='High'}else if(low>=CFG.comfortableFt){status='Comfortable';confidence='High'}else if(low<CFG.crowdFt&&high>=CFG.crowdFt)status='Uncertain / Could Be Too Close';else if(low>=CFG.crowdFt&&high<CFG.comfortableFt)status='Close';else status='Uncertain / Near Comfort Boundary';return {status,confidence,distanceFeet:ft,possibleMinFeet:low,possibleMaxFeet:high};}
function movementSummary(events:E[],refs:any[]){const crumbs=events.filter(e=>e.event_type==='breadcrumb'&&verified(e)).sort((a,b)=>+new Date(a.event_time)-+new Date(b.event_time));let walk=0;const speeds:number[]=[];for(let i=1;i<crumbs.length;i++){const sec=(+new Date(crumbs[i].event_time)-+new Date(crumbs[i-1].event_time))/1000;if(sec<=0)continue;const d=dist(crumbs[i-1],crumbs[i])??0,s=d/sec;walk+=d;if(s>=CFG.walkMin&&s<=CFG.walkMax)speeds.push(s)}
 const stops:any[]=[];let c:any=null;for(const p of crumbs){const t=+new Date(p.event_time);if(!c){c={start:t,last:t,anchor:p,nearest:nearestRef(p,refs),maxRadius:0};continue}const d=dist(c.anchor,p)??999;if(d<=CFG.stopRadius){c.last=t;c.maxRadius=Math.max(c.maxRadius,d);const nr=nearestRef(p,refs);if(nr!=null&&(c.nearest==null||nr<c.nearest))c.nearest=nr}else{const dur=c.last-c.start;if(dur>=CFG.stopMinMs)stops.push({...c,durationMs:dur});c={start:t,last:t,anchor:p,nearest:nearestRef(p,refs),maxRadius:0}}}if(c){const dur=c.last-c.start;if(dur>=CFG.stopMinMs)stops.push({...c,durationMs:dur})}
 const off=stops.filter(s=>s.nearest==null||s.nearest>CFG.offRoute),long=off.filter(s=>s.durationMs>=CFG.longIdleMs);return {avgWalkingMps:speeds.length?speeds.reduce((a,b)=>a+b,0)/speeds.length:null,totalWalkDistanceMeters:walk,stopCount:stops.length,offRouteStopCount:off.length,offRouteIdleMs:off.reduce((a,b)=>a+b.durationMs,0),longOffRouteStopCount:long.length,longOffRouteStops:long.map(s=>({durationMs:s.durationMs,nearestDoorMeters:s.nearest,latitude:s.anchor.latitude,longitude:s.anchor.longitude}))};}
function nearestRef(p:E,refs:any[]){let best:number|null=null;for(const r of refs){const d=dist(p,r);if(d!=null&&(best==null||d<best))best=d}return best;}
function doorZoneSummaries(events:E[],doors:Map<string,any>){const out:any[]=[];const arrivals=events.filter(e=>e.event_type==='door_arrival'&&e.lead_label).sort((a,b)=>+new Date(a.event_time)-+new Date(b.event_time));for(const a of arrivals){const end=events.find(e=>e.event_type==='disposition'&&e.lead_label===a.lead_label&&+new Date(e.event_time)>=+new Date(a.event_time));if(!end)continue;const door=doors.get(a.lead_label!);const ref=door|| (a.lead_latitude!=null?{latitude:a.lead_latitude,longitude:a.lead_longitude}:null);if(!ref)continue;const pts=[a,...events.filter(e=>e.event_type==='breadcrumb'&&+new Date(e.event_time)>+new Date(a.event_time)&&+new Date(e.event_time)<+new Date(end.event_time)),end].filter(e=>e.latitude!=null).sort((x,y)=>+new Date(x.event_time)-+new Date(y.event_time));let inside=0,away=0,max=0;for(let i=1;i<pts.length;i++){const dt=+new Date(pts[i].event_time)-+new Date(pts[i-1].event_time),d=dist(pts[i-1],ref)??999;max=Math.max(max,d);if(d<=CFG.doorZone)inside+=dt;else away+=dt}out.push({lead:a.lead_label,disposition:end.disposition,totalMs:+new Date(end.event_time)-+new Date(a.event_time),doorZoneMs:inside,awayZoneMs:away,maxDistanceMeters:max})}return out;}
function coaching(summary:any){const s:string[]=[];if(summary.movement.longOffRouteStopCount>0)s.push('Review prolonged off-route stationary blocks.');if(summary.movement.avgWalkingMps!=null&&summary.movement.avgWalkingMps<0.7)s.push('Walking pace is low for sustained field movement; review route flow and context.');if(summary.doorZones.some((z:any)=>z.awayZoneMs>z.doorZoneMs&&z.totalMs>60000))s.push('Some long visits contain more away-from-door time than door-zone time.');if(summary.comfort.some((x:any)=>x.status==='Likely Too Close'))s.push('Review customer-spacing coaching for likely crowding at learned doors.');if(!s.length)s.push('No major coaching flags detected in this session.');return s;}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{const auth=req.headers.get('Authorization')||'';const jwt=auth.replace(/^Bearer\s+/,'');if(!jwt)return Response.json({error:'unauthorized'},{status:401,headers:corsHeaders});const url=Deno.env.get('SUPABASE_URL')!;const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:uerr}=await admin.auth.getUser(jwt);if(uerr||!user?.email)return Response.json({error:'unauthorized'},{status:401,headers:corsHeaders});const {data:access}=await admin.from('app_user_access').select('role,active').eq('email',user.email.toLowerCase()).maybeSingle();if(!access?.active||!['admin','manager','trainer'].includes(access.role))return Response.json({error:'forbidden'},{status:403,headers:corsHeaders});const body=await req.json().catch(()=>({}));const sessionId=body.session_id;let session:any=null;if(sessionId){const {data}=await admin.from('test_sessions').select('*').eq('id',sessionId).maybeSingle();session=data}else{const {data}=await admin.from('test_sessions').select('*').order('started_at',{ascending:false}).limit(1).maybeSingle();session=data}if(!session)return Response.json({error:'session_not_found'},{status:404,headers:corsHeaders});const {data:events,error:eerr}=await admin.from('test_events').select('*').eq('session_id',session.id).order('event_time',{ascending:true});if(eerr)throw eerr;const es=(events||[]) as E[];
 const leadNames=[...new Set(es.filter(e=>e.lead_label&&['door_arrival','disposition'].includes(e.event_type)).map(e=>e.lead_label!))];const doors=new Map<string,any>();const walkwayOffsets:number[]=[];for(const lead of leadNames){const {data:hist}=await admin.from('test_events').select('*').eq('lead_label',lead).eq('event_type','disposition').order('event_time',{ascending:false}).limit(200);const valid=(hist||[] as E[]).filter((e:any)=>verified(e)&&propertyStatus(e)!=='Outside Property Area');const model=pointMedian(valid as E[]);if(model){doors.set(lead,model);await admin.from('observed_door_models').upsert({lead_key:lead,observed_latitude:model.latitude,observed_longitude:model.longitude,verified_visit_count:model.count,updated_at:new Date().toISOString()});}
 const visits=es.filter(e=>e.lead_label===lead&&e.event_type==='disposition'&&verified(e));for(const v of visits){const t=+new Date(v.event_time);const nearby=es.filter(e=>e.event_type==='breadcrumb'&&verified(e)&&+new Date(e.event_time)<=t&&t-+new Date(e.event_time)<=120000);let best:number|null=null;for(const b of nearby){const d=dist(v,b);if(d!=null&&d>=8&&d<=60&&(best==null||d<best))best=d}if(best!=null)walkwayOffsets.push(best)}if(model&&walkwayOffsets.length){await admin.from('observed_door_models').update({walkway_offset_meters:median(walkwayOffsets),walkway_sample_count:walkwayOffsets.length,updated_at:new Date().toISOString()}).eq('lead_key',lead)}}
 const refs=[...doors.values()];for(const e of es){if(e.lead_latitude!=null&&e.lead_longitude!=null)refs.push({latitude:e.lead_latitude,longitude:e.lead_longitude})}
 const movement=movementSummary(es,refs),doorZones=doorZoneSummaries(es,doors);const comfort=es.filter(e=>e.event_type==='disposition'&&e.lead_label).map(e=>({lead:e.lead_label,disposition:e.disposition,...comfort(e,doors.get(e.lead_label!))}));const dispositions=es.filter(e=>e.event_type==='disposition');const avg=(name:string)=>{const x=dispositions.filter(e=>e.disposition===name&&e.dwell_ms!=null);return x.length?x.reduce((a,e)=>a+(e.dwell_ms||0),0)/x.length:null};const {data:ruleRow}=await admin.from('compensation_rules').select('rule').eq('active',true).order('id').limit(1).maybeSingle();const rule=ruleRow?.rule||{};const saleCount=dispositions.filter(e=>e.disposition===(rule.sale_disposition||'Sale')).length;let perSale=Number(rule.base_per_sale||0);for(const tier of (rule.weekly_tiers||[])){if(saleCount>=Number(tier.min_sales||0))perSale=Math.max(perSale,Number(tier.per_sale||perSale))}const compensation={saleCount,perSale,estimatedGross:saleCount*perSale,ruleKey:ruleRow?'configured':'none'};
 const summary:any={engineVersion:ENGINE,session:{id:session.id,testerName:session.tester_name,testerEmail:session.tester_email,startedAt:session.started_at,appVersion:session.app_version},counts:{events:es.length,doors:dispositions.length,contacts:dispositions.filter(e=>['Contacted','Interested','Follow Up','Sale','Not Interested'].includes(e.disposition||'')).length,sales:saleCount},dwell:{notHomeMs:avg('Not Home'),contactedMs:avg('Contacted'),saleMs:avg('Sale')},movement,doorModels:[...doors.entries()].map(([lead,m])=>({lead,verifiedVisitCount:m.count,learnedWalkwayOffsetMeters:median(walkwayOffsets)})),doorZones,comfort,compensation};summary.coaching=coaching(summary);await admin.from('field_analytics_results').upsert({session_id:session.id,engine_version:ENGINE,summary,generated_at:new Date().toISOString()},{onConflict:'session_id,engine_version'});return Response.json({ok:true,role:access.role,summary},{headers:{...corsHeaders,'Cache-Control':'no-store'}})}catch(err){console.error(err);return Response.json({error:'analytics_failed'},{status:500,headers:corsHeaders})}})
