-- Synthetic production-contract subset for local Live Feed validation only.
-- This file contains no production data and is never applied to a hosted project.
-- It defines only the objects required by the preview migration and rollback canary.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated, service_role;

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  legal_name text not null,
  display_name text not null,
  billing_status text not null default 'trial_active',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  role text not null,
  active boolean not null default true,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, auth_user_id)
);

create table public.app_user_access (
  email text primary key,
  role text not null,
  active boolean not null default true,
  display_name text,
  created_at timestamptz not null default now(),
  organization_id uuid not null references public.organizations(id) on delete cascade
);

create table public.users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  role text not null default 'rep',
  team_id uuid,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  organization_id uuid not null references public.organizations(id) on delete cascade
);

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  manager_user_id uuid references public.users(id) on delete set null,
  organization_id uuid not null references public.organizations(id) on delete cascade
);

alter table public.users
  add constraint users_team_id_fkey
  foreign key (team_id) references public.teams(id) on delete set null;

create table public.sales_records (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  rep_user_id uuid not null references public.users(id) on delete restrict,
  rep_email text not null,
  rep_name text not null,
  isp text not null,
  sale_status text not null default 'reported',
  verification_status text not null default 'pending_verification',
  ranking_eligible boolean not null default false,
  compensation_snapshot jsonb not null default '{}'::jsonb
);

create table public.sales_feed (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sale_id uuid not null references public.sales_records(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  rep_user_id uuid not null references public.users(id) on delete restrict,
  rep_name text not null,
  isp text not null,
  message text not null,
  celebration_types text[] not null default '{}'::text[],
  celebration_messages jsonb not null default '[]'::jsonb,
  celebration_version integer not null default 0,
  animation_enabled boolean not null default false,
  ranking_eligible_at_event boolean not null default false
);

create or replace function private.current_organization_id()
returns uuid
language sql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
  select membership.organization_id
  from public.organization_memberships membership
  where membership.auth_user_id = auth.uid()
    and membership.active
  order by membership.is_default desc, membership.created_at asc
  limit 1
$$;

create or replace function private.mccoy_organization_id()
returns uuid
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select organization.id
  from public.organizations organization
  where organization.slug = 'mccoy-platform-llc'
  limit 1
$$;

create or replace function private.organization_access_allowed(
  p_organization_id uuid,
  p_entitlement text default 'field_coach_access'
)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1
    from public.organizations organization
    where organization.id = p_organization_id
      and organization.active
      and organization.billing_status in (
        'internal_unlimited',
        'trial_active',
        'active',
        'grace'
      )
      and p_entitlement = 'field_coach_access'
  )
$$;

revoke all on function private.current_organization_id() from public, anon, authenticated;
revoke all on function private.mccoy_organization_id() from public, anon, authenticated;
revoke all on function private.organization_access_allowed(uuid, text) from public, anon, authenticated;

-- Local Supabase normally creates this publication. Keep the fixture self-contained
-- for CLI image changes or reduced-service startup modes.
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
end;
$$;
