import { createClient } from 'npm:@supabase/supabase-js@2.95.0'
import { corsHeaders } from 'npm:@supabase/supabase-js@2.95.0/cors'
const R=6371000,toRad=(x:number)=>x*Math.PI/180;
function dist(a:any,b:any){if(!a||!b||a.latitude==null||a.longitude==null||b.latitude==null||b.longitude==null)return null;const dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{
 const auth=req.headers.get('Authorization')||'',jwt=auth.replace(/^Bearer\s+/,'');if(!jwt)return Response.json({error:'unauthorized'},{status:401,headers:corsHeaders});
 const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 const {data:{user},error:uerr}=await admin.auth.getUser(jwt);if(uerr||!user?.email)return Response.json({error:'unauthorized'},{status:401,headers:corsHeaders});
 const viewerEmail=user.email.toLowerCase();const {data:viewer}=await admin.from('app_user_access').select('active,role,display_name,assigned_manager_email').eq('email',viewerEmail).maybeSingle();if(!viewer?.active)return Response.json({error:'forbidden'},{status:403,headers:corsHeaders});
 const {data:global}=await admin.from('metrics_visibility_settings').select('*').order('id').limit(1).maybeSingle();
 const body=await req.json().catch(()=>({}));let targetEmail=String(body.tester_email||viewerEmail).trim().toLowerCase();
 const {data:targetAccess}=await admin.from('app_user_access').select('email,active,display_name,assigned_manager_email,assigned_manager_name').eq('email',targetEmail).maybeSingle();if(!targetAccess?.active)return Response.json({error:'tester_not_found'},{status:404,headers:corsHeaders});
 const {data:per}=await admin.from('rep_metrics_visibility').select('*').eq('rep_email',targetEmail).maybeSingle();
 const repEnabled=!!global?.global_rep_metrics_enabled && !!per?.rep_metrics_enabled;
 const mgrEnabled=!!global?.global_manager_metrics_enabled && (per?.manager_metrics_enabled ?? true);
 let allowed=false,scope='none';
 if(viewer.role==='admin'){allowed=true;scope='admin';}
 else if(viewerEmail===targetEmail && repEnabled){allowed=true;scope='self';}
 else if(['manager','trainer'].includes(viewer.role) && mgrEnabled && (targetAccess.assigned_manager_email||'').toLowerCase()===viewerEmail){allowed=true;scope=viewer.role;}
 if(!allowed)return Response.json({error:'metrics_hidden'},{status:403,headers:corsHeaders});
 const {data:{users}}=await admin.auth.admin.listUsers({page:1,perPage:1000});const au=users.find((x:any)=>x.email?.toLowerCase()===targetEmail);if(!au)return Response.json({error:'tester_auth_not_found'},{status:404,headers:corsHeaders});
 let q=admin.from('test_sessions').select('*').eq('tester_user_id',au.id).order('started_at',{ascending:false}).limit(1);if(body.session_id)q=admin.from('test_sessions').select('*').eq('tester_user_id',au.id).eq('id',body.session_id).limit(1);const {data:sessions}=await q;const s=sessions?.[0];if(!s)return Response.json({ok:true,summary:null,target_email:targetEmail,scope},{headers:{...corsHeaders,'Cache-Control':'no-store'}});
 const {data:events,error:eerr}=await admin.from('test_events').select('*').eq('session_id',s.id).order('event_time',{ascending:true});if(eerr)throw eerr;const es=events||[];
 const crumbs=es.filter((e:any)=>e.event_type==='breadcrumb'&&e.latitude!=null&&e.longitude!=null);let distance=0,movingMs=0;const speeds:number[]=[];for(let i=1;i<crumbs.length;i++){const dt=+new Date(crumbs[i].event_time)-+new Date(crumbs[i-1].event_time);if(dt<=0)continue;const d=dist(crumbs[i-1],crumbs[i])||0;distance+=d;const sp=d/(dt/1000);if(sp>=0.4&&sp<=3.0){movingMs+=dt;speeds.push(sp)}}
 const gps=es.filter((e:any)=>e.accuracy_meters!=null).map((e:any)=>Number(e.accuracy_meters));const dispositions=es.filter((e:any)=>e.event_type==='disposition');const avg=(name:string)=>{const a=dispositions.filter((e:any)=>e.disposition===name&&e.dwell_ms!=null);return a.length?Math.round(a.reduce((x:number,e:any)=>x+Number(e.dwell_ms||0),0)/a.length):null};
 const transitions=es.filter((e:any)=>e.event_type==='transition_interval');const transitionMs=transitions.map((e:any)=>Number(e.dwell_ms??e.payload?.transitionElapsedMs??0)).filter((x:number)=>x>0);const autos=es.filter((e:any)=>e.event_type==='auto_stop');
 const doors=es.filter((e:any)=>e.event_type==='door_arrival').length,contacts=dispositions.filter((e:any)=>['Contacted','Interested','Follow Up','Sale','Not Interested'].includes(e.disposition)).length,sales=dispositions.filter((e:any)=>e.disposition==='Sale').length;const durationMs=(s.ended_at?+new Date(s.ended_at):Date.now())-(+new Date(s.started_at));
 const summary={tester_email:s.tester_email||targetEmail,tester_name:s.tester_name,session_id:s.id,started_at:s.started_at,ended_at:s.ended_at,app_version:s.app_version,duration_ms:Math.max(0,durationMs),event_count:es.length,doors,contacts,sales,dispositions:dispositions.reduce((o:any,e:any)=>(o[e.disposition]=(o[e.disposition]||0)+1,o),{}),gps:{samples:gps.length,average_accuracy_m:gps.length?gps.reduce((a:number,b:number)=>a+b,0)/gps.length:null,best_accuracy_m:gps.length?Math.min(...gps):null,worst_accuracy_m:gps.length?Math.max(...gps):null},movement:{distance_m:distance,average_moving_speed_mps:speeds.length?speeds.reduce((a,b)=>a+b,0)/speeds.length:null,moving_ms:movingMs},dwell:{not_home_ms:avg('Not Home'),contacted_ms:avg('Contacted'),sale_ms:avg('Sale')},transition:{count:transitionMs.length,average_ms:transitionMs.length?Math.round(transitionMs.reduce((a,b)=>a+b,0)/transitionMs.length):null,last_ms:transitionMs.length?transitionMs[transitionMs.length-1]:null},auto_stop:autos.length?{reason:autos[autos.length-1].payload?.reason||'auto_stop',event_time:autos[autos.length-1].event_time}:null};
 return Response.json({ok:true,scope,summary},{headers:{...corsHeaders,'Cache-Control':'no-store'}});
}catch(e){console.error(e);return Response.json({error:'rep_coach_summary_failed'},{status:500,headers:corsHeaders})}});
