-- Authoritative Sales/Hour workday model.
--
-- The denominator is independent of the Start/Stop Knocking button. McCoy
-- records consented, authenticated presence while the app is open and keeps a
-- server-owned daily window. Explicit field areas are preferred; assigned,
-- geocoded leads are the fallback area. Sunday is excluded and one lunch hour
-- is deducted per counted day.

create table if not exists public.sph_rep_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  home_label text,
  home_latitude double precision,
  home_longitude double precision,
  home_accuracy_meters double precision,
  updated_at timestamptz not null default clock_timestamp(),
  constraint sph_rep_settings_home_pair check (
    (home_latitude is null and home_longitude is null)
    or (home_latitude between -90 and 90 and home_longitude between -180 and 180)
  ),
  constraint sph_rep_settings_home_accuracy check (
    home_accuracy_meters is null or home_accuracy_meters between 0 and 100
  ),
  constraint sph_rep_settings_label_length check (
    home_label is null or char_length(home_label) between 1 and 200
  )
);

create table if not exists public.sph_presence_events (
  id bigint generated by default as identity primary key,
  rep_user_id uuid not null references auth.users(id) on delete cascade,
  event_at timestamptz not null default clock_timestamp(),
  event_type text not null,
  latitude double precision,
  longitude double precision,
  accuracy_meters double precision,
  inside_area boolean,
  distance_outside_area_m double precision,
  distance_home_m double precision,
  area_basis text not null default 'none',
  source_test_event_id bigint references public.test_events(id) on delete set null,
  created_at timestamptz not null default clock_timestamp(),
  constraint sph_presence_event_type_check check (
    event_type in ('login','heartbeat','sale','field_start','field_end','home_update','historical')
  ),
  constraint sph_presence_coordinate_pair check (
    (latitude is null and longitude is null)
    or (latitude between -90 and 90 and longitude between -180 and 180)
  ),
  constraint sph_presence_accuracy_check check (
    accuracy_meters is null or accuracy_meters between 0 and 10000
  ),
  constraint sph_presence_area_basis_check check (
    area_basis in ('explicit_assignment','assigned_leads','none','unverified_gps')
  )
);

create unique index if not exists sph_presence_source_test_event_uidx
  on public.sph_presence_events(source_test_event_id)
  where source_test_event_id is not null;
create index if not exists sph_presence_rep_time_idx
  on public.sph_presence_events(rep_user_id,event_at desc);
create index if not exists sph_presence_rep_inside_time_idx
  on public.sph_presence_events(rep_user_id,event_at)
  where inside_area is not null;

create table if not exists public.sph_home_setting_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid not null references auth.users(id),
  action text not null default 'home_location_updated',
  changed_at timestamptz not null default clock_timestamp(),
  constraint sph_home_setting_action_check check (action in ('home_location_updated','home_location_cleared'))
);
create index if not exists sph_home_setting_audit_user_time_idx
  on public.sph_home_setting_audit(user_id,changed_at desc);

alter table public.sph_rep_settings enable row level security;
alter table public.sph_presence_events enable row level security;
alter table public.sph_home_setting_audit enable row level security;
revoke all on table public.sph_rep_settings, public.sph_presence_events, public.sph_home_setting_audit
  from public, anon, authenticated;
revoke all on sequence public.sph_presence_events_id_seq, public.sph_home_setting_audit_id_seq
  from public, anon, authenticated;

create index if not exists leads_assigned_rep_geocoded_idx
  on public.leads(assigned_rep_id)
  where latitude is not null and longitude is not null;
create index if not exists leads_assigned_manager_geocoded_idx
  on public.leads(assigned_manager_id)
  where latitude is not null and longitude is not null;
create index if not exists leads_assigned_admin_geocoded_idx
  on public.leads(lower(assigned_admin_email))
  where latitude is not null and longitude is not null and assigned_admin_email is not null;

create or replace function private.sph_area_snapshot(
  p_auth_user_id uuid,
  p_latitude double precision,
  p_longitude double precision
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $function$
declare
  v_email text;
  v_role text;
  v_profile_id uuid;
  v_distance double precision;
  v_count bigint;
  v_basis text := 'none';
begin
  if p_auth_user_id is null
     or p_latitude is null or p_latitude not between -90 and 90
     or p_longitude is null or p_longitude not between -180 and 180 then
    return jsonb_build_object('inside_area',null,'distance_outside_area_m',null,'area_basis','unverified_gps');
  end if;

  select lower(trim(au.email)), lower(trim(a.role)), u.id
  into v_email, v_role, v_profile_id
  from auth.users au
  join public.app_user_access a on lower(trim(a.email))=lower(trim(au.email)) and a.active is true
  left join public.users u on lower(trim(u.email))=lower(trim(au.email)) and u.active is true
  where au.id=p_auth_user_id;
  if v_email is null then
    return jsonb_build_object('inside_area',null,'distance_outside_area_m',null,'area_basis','none');
  end if;

  select min(private.mccoy_distance_meters(
      p_latitude,p_longitude,f.center_latitude,f.center_longitude
    )-f.radius_m), count(*)
  into v_distance,v_count
  from public.field_area_assignments f
  where f.user_id=p_auth_user_id and f.active is true;

  if coalesce(v_count,0)>0 then
    v_basis:='explicit_assignment';
  else
    select min(private.mccoy_distance_meters(
      p_latitude,p_longitude,l.latitude,l.longitude
    )-402.336), count(*)
    into v_distance,v_count
    from public.leads l
    where l.latitude is not null and l.longitude is not null
      and (
        (v_role in ('rep','tester') and v_profile_id is not null and l.assigned_rep_id=v_profile_id)
        or (v_role in ('manager','trainer') and v_profile_id is not null and l.assigned_manager_id=v_profile_id)
        or (v_role='admin' and lower(coalesce(l.assigned_admin_email,''))=v_email)
      );
    if coalesce(v_count,0)>0 then v_basis:='assigned_leads'; end if;
  end if;

  if coalesce(v_count,0)=0 or v_distance is null then
    return jsonb_build_object('inside_area',false,'distance_outside_area_m',null,'area_basis','none');
  end if;
  return jsonb_build_object(
    'inside_area',v_distance<=0,
    'distance_outside_area_m',greatest(v_distance,0),
    'area_basis',v_basis
  );
end;
$function$;

revoke all on function private.sph_area_snapshot(uuid,double precision,double precision)
  from public,anon,authenticated;

create or replace function public.record_sph_presence(
  p_event_type text default 'heartbeat',
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_accuracy_meters double precision default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth, private
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_event_type text := lower(trim(coalesce(p_event_type,'heartbeat')));
  v_access public.app_user_access%rowtype;
  v_notice text;
  v_consented boolean := false;
  v_area jsonb;
  v_home public.sph_rep_settings%rowtype;
  v_home_distance double precision;
  v_existing public.sph_presence_events%rowtype;
  v_row public.sph_presence_events%rowtype;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  select a.* into v_access from public.app_user_access a
  join auth.users au on lower(trim(au.email))=lower(trim(a.email))
  where au.id=v_uid and a.active is true;
  if not found then raise exception 'active_mccoy_access_required' using errcode='42501'; end if;
  if v_event_type not in ('login','heartbeat','sale','field_start','field_end','home_update') then
    raise exception 'invalid_sph_event_type' using errcode='22023';
  end if;
  if (p_latitude is null) <> (p_longitude is null) then
    raise exception 'coordinate_pair_required' using errcode='22023';
  end if;
  if p_latitude is not null and (p_latitude not between -90 and 90 or p_longitude not between -180 and 180) then
    raise exception 'invalid_coordinates' using errcode='22023';
  end if;
  if p_accuracy_meters is not null and p_accuracy_meters not between 0 and 10000 then
    raise exception 'invalid_location_accuracy' using errcode='22023';
  end if;

  if p_latitude is not null then
    select value into v_notice from public.app_config where key='privacy_notice_version';
    select exists(select 1 from public.privacy_acceptances p
      where p.user_id=v_uid and p.notice_version=v_notice
        and p.precise_location_consent is true and p.work_activity_analytics_consent is true)
    into v_consented;
    if not v_consented then raise exception 'current_privacy_consent_required' using errcode='42501'; end if;
  end if;

  if v_event_type='heartbeat' then
    select * into v_existing from public.sph_presence_events
    where rep_user_id=v_uid and event_type='heartbeat' and event_at>clock_timestamp()-interval '60 seconds'
    order by event_at desc limit 1;
    if found then return jsonb_build_object('ok',true,'duplicate_suppressed',true,
      'inside_area',v_existing.inside_area,'area_basis',v_existing.area_basis); end if;
  end if;

  if p_latitude is not null and coalesce(p_accuracy_meters,0)<=100 then
    v_area:=private.sph_area_snapshot(v_uid,p_latitude,p_longitude);
  else
    v_area:=jsonb_build_object('inside_area',null,'distance_outside_area_m',null,
      'area_basis',case when p_latitude is null then 'none' else 'unverified_gps' end);
  end if;
  select * into v_home from public.sph_rep_settings where user_id=v_uid;
  if p_latitude is not null and v_home.home_latitude is not null then
    v_home_distance:=private.mccoy_distance_meters(p_latitude,p_longitude,v_home.home_latitude,v_home.home_longitude);
  end if;

  insert into public.sph_presence_events(
    rep_user_id,event_type,latitude,longitude,accuracy_meters,inside_area,
    distance_outside_area_m,distance_home_m,area_basis
  ) values(
    v_uid,v_event_type,p_latitude,p_longitude,p_accuracy_meters,
    (v_area->>'inside_area')::boolean,(v_area->>'distance_outside_area_m')::double precision,
    v_home_distance,coalesce(v_area->>'area_basis','none')
  ) returning * into v_row;
  return jsonb_build_object('ok',true,'event_at',v_row.event_at,'inside_area',v_row.inside_area,
    'area_basis',v_row.area_basis,'home_configured',v_home.home_latitude is not null);
end;
$function$;

revoke all on function public.record_sph_presence(text,double precision,double precision,double precision)
  from public,anon;
grant execute on function public.record_sph_presence(text,double precision,double precision,double precision)
  to authenticated;

create or replace function public.set_sph_home_location(
  p_home_label text,
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_meters double precision
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_label text := nullif(trim(regexp_replace(coalesce(p_home_label,'Home'),'\s+',' ','g')),'');
  v_notice text;
  v_access boolean;
  v_consented boolean;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  select exists(select 1 from auth.users au join public.app_user_access a
    on lower(trim(a.email))=lower(trim(au.email)) where au.id=v_uid and a.active is true) into v_access;
  if not v_access then raise exception 'active_mccoy_access_required' using errcode='42501'; end if;
  if v_label is null or char_length(v_label)>200 then raise exception 'valid_home_label_required' using errcode='22023'; end if;
  if p_latitude is null or p_latitude not between -90 and 90
     or p_longitude is null or p_longitude not between -180 and 180
     or p_accuracy_meters is null or p_accuracy_meters not between 0 and 100 then
    raise exception 'accurate_home_location_required' using errcode='22023';
  end if;
  select value into v_notice from public.app_config where key='privacy_notice_version';
  select exists(select 1 from public.privacy_acceptances p where p.user_id=v_uid
    and p.notice_version=v_notice and p.precise_location_consent is true
    and p.work_activity_analytics_consent is true) into v_consented;
  if not v_consented then raise exception 'current_privacy_consent_required' using errcode='42501'; end if;

  insert into public.sph_rep_settings(user_id,home_label,home_latitude,home_longitude,home_accuracy_meters,updated_at)
  values(v_uid,v_label,p_latitude,p_longitude,p_accuracy_meters,clock_timestamp())
  on conflict(user_id) do update set home_label=excluded.home_label,
    home_latitude=excluded.home_latitude,home_longitude=excluded.home_longitude,
    home_accuracy_meters=excluded.home_accuracy_meters,updated_at=excluded.updated_at;
  insert into public.sph_home_setting_audit(user_id,changed_by,action)
  values(v_uid,v_uid,'home_location_updated');
  return jsonb_build_object('ok',true,'home_configured',true,'home_label',v_label);
end;
$function$;

revoke all on function public.set_sph_home_location(text,double precision,double precision,double precision)
  from public,anon;
grant execute on function public.set_sph_home_location(text,double precision,double precision,double precision)
  to authenticated;

-- Backfill is deliberately bounded so a large lead pool cannot hold an
-- activation migration open. Operations invokes this repeatedly after the
-- schema is active; each call is idempotent through source_test_event_id.
create or replace function private.backfill_sph_presence(p_limit integer default 200)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public, auth, private
as $function$
declare v_count integer:=0;
begin
  if p_limit is null or p_limit not between 1 and 500 then raise exception 'backfill_limit_1_to_500' using errcode='22023';end if;
  with raw_candidates as (
    select e.*,s.tester_user_id,
      row_number() over(
        partition by s.tester_user_id,date_bin(interval '5 minutes',e.event_time,timestamptz '2000-01-01 00:00:00+00')
        order by e.event_time,e.id
      ) bucket_rank
    from public.test_events e
    join public.test_sessions s on s.id=e.session_id and s.tester_user_id is not null
    where e.latitude is not null and e.longitude is not null
      and coalesce(e.accuracy_meters,0)<=100
      and e.event_time>=date_trunc('week',timezone('America/Los_Angeles',clock_timestamp())) at time zone 'America/Los_Angeles'
  ), candidates as (
    select e.*
    from raw_candidates e
    where (e.bucket_rank=1
      or e.event_type in ('session_start','session_end')
      or (e.event_type='disposition' and lower(coalesce(e.disposition,''))='sale'))
      and not exists(select 1 from public.sph_presence_events p where p.source_test_event_id=e.id)
    order by e.id
    limit p_limit
  )
  insert into public.sph_presence_events(
    rep_user_id,event_at,event_type,latitude,longitude,accuracy_meters,
    inside_area,distance_outside_area_m,distance_home_m,area_basis,source_test_event_id
  )
  select e.tester_user_id,e.event_time,
    case when e.event_type='session_start' then 'field_start'
         when e.event_type='session_end' then 'field_end'
         when e.event_type='disposition' and lower(coalesce(e.disposition,''))='sale' then 'sale'
         else 'historical' end,
    e.latitude,e.longitude,e.accuracy_meters,
    (area.snapshot->>'inside_area')::boolean,
    (area.snapshot->>'distance_outside_area_m')::double precision,
    case when h.home_latitude is not null then private.mccoy_distance_meters(
      e.latitude,e.longitude,h.home_latitude,h.home_longitude) end,
    coalesce(area.snapshot->>'area_basis','none'),e.id
  from candidates e
  left join public.sph_rep_settings h on h.user_id=e.tester_user_id
  cross join lateral (select private.sph_area_snapshot(e.tester_user_id,e.latitude,e.longitude) snapshot) area
  on conflict(source_test_event_id) where source_test_event_id is not null do nothing;
  get diagnostics v_count=row_count;
  return v_count;
end;
$function$;
revoke all on function private.backfill_sph_presence(integer) from public,anon,authenticated;
grant execute on function private.backfill_sph_presence(integer) to service_role;

create or replace function private.get_authoritative_sph_metrics()
returns table(rep_name text, role text, team_name text, metric jsonb, sph_rank integer)
language sql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $function$
with
settings as (select lower(trim(ghost_email)) ghost_email from public.ghost_ranking_settings where singleton is true),
bounds as (
  select timezone('America/Los_Angeles',clock_timestamp())::date today,
    date_trunc('week',timezone('America/Los_Angeles',clock_timestamp()))::date week_start,
    clock_timestamp() now_at
),
accounts as (
  select au.id auth_user_id,lower(trim(a.email)) email,
    coalesce(nullif(trim(a.display_name),''),'Rep') rep_name,
    lower(a.role) role,nullif(trim(a.team_name),'') team_name
  from public.app_user_access a
  join auth.users au on lower(trim(au.email))=lower(trim(a.email))
  cross join settings s
  where a.active is true and lower(trim(a.email))<>s.ghost_email
),
eligible_sales as (
  select lower(trim(sr.rep_email)) email,coalesce(p.sale_date,sr.created_at) sale_at
  from public.sales_records sr
  left join public.provider_sales_rows p on p.id=sr.provider_sale_row_id
  cross join settings s
  where sr.ranking_eligible is true and sr.verification_status='verified_processed'
    and lower(trim(sr.rep_email))<>s.ghost_email
    and (coalesce(sr.compensation_snapshot->>'sale_origin','')<>'outside_system'
      or lower(coalesce(sr.compensation_snapshot#>>'{admin_approval,status}',''))='approved')
    and (coalesce(sr.compensation_snapshot->>'sale_context','')<>'out_of_area_phone'
      or lower(coalesce(sr.compensation_snapshot#>>'{admin_approval,status}',''))='approved')
),
login_days as (
  select pe.rep_user_id auth_user_id,timezone('America/Los_Angeles',pe.event_at)::date work_date,min(pe.event_at) first_login
  from public.sph_presence_events pe cross join bounds b
  where pe.event_type='login' and pe.event_at>=b.week_start::timestamp at time zone 'America/Los_Angeles'
  group by pe.rep_user_id,timezone('America/Los_Angeles',pe.event_at)::date
  union all
  select ts.tester_user_id,timezone('America/Los_Angeles',ts.started_at)::date,min(ts.started_at)
  from public.test_sessions ts cross join bounds b
  where ts.tester_user_id is not null and ts.started_at>=b.week_start::timestamp at time zone 'America/Los_Angeles'
  group by ts.tester_user_id,timezone('America/Los_Angeles',ts.started_at)::date
  union all
  select s.user_id,timezone('America/Los_Angeles',s.created_at)::date,min(s.created_at)
  from auth.sessions s cross join bounds b
  where s.created_at>=b.week_start::timestamp at time zone 'America/Los_Angeles'
  group by s.user_id,timezone('America/Los_Angeles',s.created_at)::date
),
sales_days as (
  select a.auth_user_id,timezone('America/Los_Angeles',e.sale_at)::date work_date,
    min(e.sale_at) first_sale,max(e.sale_at) last_sale
  from eligible_sales e join accounts a using(email) cross join bounds b
  where e.sale_at>=b.week_start::timestamp at time zone 'America/Los_Angeles'
  group by a.auth_user_id,timezone('America/Los_Angeles',e.sale_at)::date
),
presence_days as (
  select p.rep_user_id auth_user_id,timezone('America/Los_Angeles',p.event_at)::date work_date
  from public.sph_presence_events p cross join bounds b
  where p.event_at>=b.week_start::timestamp at time zone 'America/Los_Angeles'
  group by p.rep_user_id,timezone('America/Los_Angeles',p.event_at)::date
),
activity_days as (
  select auth_user_id,work_date from login_days
  union select auth_user_id,work_date from sales_days
  union select auth_user_id,work_date from presence_days
),
days as (
  select a.*,d.work_date
  from accounts a join activity_days d using(auth_user_id) cross join bounds b
  where d.work_date between b.week_start and b.today
    and extract(isodow from d.work_date)<>7
),
points0 as (
  select p.*,
    lag(p.event_at) over(partition by p.rep_user_id,timezone('America/Los_Angeles',p.event_at)::date order by p.event_at,p.id) prev_at,
    lag(p.inside_area) over(partition by p.rep_user_id,timezone('America/Los_Angeles',p.event_at)::date order by p.event_at,p.id) prev_inside,
    lag(p.distance_outside_area_m) over(partition by p.rep_user_id,timezone('America/Los_Angeles',p.event_at)::date order by p.event_at,p.id) prev_outside_distance,
    lag(p.distance_home_m) over(partition by p.rep_user_id,timezone('America/Los_Angeles',p.event_at)::date order by p.event_at,p.id) prev_home_distance
  from public.sph_presence_events p cross join bounds b
  where p.event_at>=b.week_start::timestamp at time zone 'America/Los_Angeles'
),
points as (
  select p.*,timezone('America/Los_Angeles',p.event_at)::date work_date,
    sum(case when p.inside_area is false and p.prev_inside is false
      and p.event_at-p.prev_at<=interval '10 minutes'
      and p.distance_outside_area_m>=coalesce(p.prev_outside_distance,0)+10 then 0 else 1 end)
      over(partition by p.rep_user_id,timezone('America/Los_Angeles',p.event_at)::date order by p.event_at,p.id) away_group
  from points0 p
),
area_entries as (
  select rep_user_id auth_user_id,work_date,min(event_at) filter(where inside_area is true) first_area_entry
  from points group by rep_user_id,work_date
),
homeward_signals as (
  select rep_user_id auth_user_id,work_date,min(event_at) signal_at
  from points
  where inside_area is false and distance_home_m is not null and prev_home_distance is not null
    and prev_home_distance-distance_home_m>=25
    and (prev_inside is true or coalesce(prev_outside_distance,0)<coalesce(distance_outside_area_m,0))
  group by rep_user_id,work_date
),
after_seven_signals as (
  select rep_user_id auth_user_id,work_date,min(event_at) signal_at
  from points
  where inside_area is false and distance_outside_area_m>=402.336
    and timezone('America/Los_Angeles',event_at)::time>=time '19:00'
  group by rep_user_id,work_date
),
away_signals as (
  select rep_user_id auth_user_id,work_date,min(max_at) signal_at
  from (
    select rep_user_id,work_date,away_group,min(event_at) min_at,max(event_at) max_at
    from points where inside_area is false
    group by rep_user_id,work_date,away_group
    having max(event_at)-min(event_at)>=interval '20 minutes'
  ) groups
  group by rep_user_id,work_date
),
signals as (
  select d.auth_user_id,d.work_date,
    least(h.signal_at,s.signal_at,w.signal_at) signal_at,
    case when least(h.signal_at,s.signal_at,w.signal_at)=h.signal_at then 'left_area_heading_home'
         when least(h.signal_at,s.signal_at,w.signal_at)=s.signal_at then 'quarter_mile_outside_after_7pm'
         when least(h.signal_at,s.signal_at,w.signal_at)=w.signal_at then 'heading_away_20_minutes'
    end signal_reason
  from days d
  left join homeward_signals h using(auth_user_id,work_date)
  left join after_seven_signals s using(auth_user_id,work_date)
  left join away_signals w using(auth_user_id,work_date)
),
window_base as (
  select d.*,
    ae.first_area_entry,
    sd.last_sale,
    sg.signal_at,sg.signal_reason,
    case when ae.first_area_entry is null
      then (d.work_date+time '11:00') at time zone 'America/Los_Angeles'
      else greatest((d.work_date+time '13:00') at time zone 'America/Los_Angeles',ae.first_area_entry)
    end window_start,
    case when ae.first_area_entry is null then
      least((d.work_date+time '19:00') at time zone 'America/Los_Angeles',
        case when d.work_date=b.today then b.now_at else (d.work_date+time '19:00') at time zone 'America/Los_Angeles' end)
      when sg.signal_at is not null then sg.signal_at
      when d.work_date=b.today then b.now_at
      else (d.work_date+time '19:00') at time zone 'America/Los_Angeles'
    end live_or_close_end,
    (ae.first_area_entry is null and b.now_at>=(d.work_date+time '19:00') at time zone 'America/Los_Angeles')
      or sg.signal_at is not null or d.work_date<b.today as is_closed
  from days d cross join bounds b
  left join area_entries ae using(auth_user_id,work_date)
  left join sales_days sd using(auth_user_id,work_date)
  left join signals sg using(auth_user_id,work_date)
),
windows as (
  select wb.*,
    greatest(wb.window_start,
      case when wb.is_closed and wb.last_sale between wb.window_start and wb.live_or_close_end
        then wb.last_sale else wb.live_or_close_end end
    ) counted_end
  from window_base wb
),
daily as (
  select w.*,
    greatest(extract(epoch from(w.counted_end-w.window_start))-3600,0)::numeric counted_seconds,
    least(greatest(extract(epoch from(w.counted_end-w.window_start)),0),3600)::numeric lunch_seconds,
    count(e.sale_at)::int sale_count
  from windows w
  left join eligible_sales e on e.email=w.email and e.sale_at between w.window_start and w.counted_end
  group by w.auth_user_id,w.email,w.rep_name,w.role,w.team_name,w.work_date,w.first_area_entry,
    w.last_sale,w.signal_at,w.signal_reason,w.window_start,w.live_or_close_end,w.is_closed,w.counted_end
),
aggregated as (
  select a.auth_user_id,a.email,a.rep_name,a.role,a.team_name,
    coalesce(round(sum(d.counted_seconds)/3600,4),0::numeric) tracked_hours,
    coalesce(sum(d.sale_count),0)::int week_sales,
    coalesce(round(sum(d.lunch_seconds)/3600,4),0::numeric) lunch_hours,
    count(d.work_date)::int days_counted,
    case when coalesce(sum(d.counted_seconds),0)>0
      then round(coalesce(sum(d.sale_count),0)::numeric/(sum(d.counted_seconds)/3600),4)
      else 0::numeric end rate
  from accounts a left join daily d on d.auth_user_id=a.auth_user_id
  group by a.auth_user_id,a.email,a.rep_name,a.role,a.team_name
),
ranked as (
  select ag.*,row_number() over(order by (tracked_hours>0) desc,rate desc,week_sales desc,
    lower(rep_name),email)::int sph_rank
  from aggregated ag
)
select r.rep_name,r.role,r.team_name,
  jsonb_build_object(
    'period','week','rate',r.rate,'tracked_hours',r.tracked_hours,'rank',r.sph_rank,
    'week_sales',r.week_sales,'qualified',r.tracked_hours>=1,'provisional',r.tracked_hours<1,
    'minimum_tracked_hours',1,'days_counted',r.days_counted,'lunch_hours_excluded',r.lunch_hours,
    'source','authenticated_mccoy_workday_area_model','active_session_button_required',false,
    'sunday_excluded',true,'daily_lunch_allowance_hours',1,
    'area_entry_start_local','13:00','no_area_fallback_local','11:00-19:00',
    'end_rules',jsonb_build_array('left_area_heading_home','quarter_mile_outside_after_7pm','heading_away_20_minutes','last_sale_when_day_closes')
  ) metric,r.sph_rank
from ranked r;
$function$;

revoke all on function private.get_authoritative_sph_metrics() from public,anon,authenticated,service_role;

create or replace function private.apply_authoritative_sph(p_item jsonb,p_map jsonb)
returns jsonb
language plpgsql
immutable
set search_path = pg_catalog
as $function$
declare v_key text;v_metric jsonb;v_item jsonb:=p_item;
begin
  if coalesce((v_item->>'is_ghost')::boolean,false) then return v_item; end if;
  v_key:=lower(trim(coalesce(v_item->>'rep_name','')))||'|'||lower(trim(coalesce(v_item->>'role','')))||'|'||lower(trim(coalesce(v_item->>'team_name','')));
  v_metric:=p_map->v_key;
  if v_metric is null then return v_item; end if;
  v_item:=jsonb_set(v_item,'{sales_per_hour}',v_metric,true);
  v_item:=jsonb_set(v_item,'{ranks,sales_per_hour}',coalesce(v_metric->'rank','null'::jsonb),true);
  return v_item;
end;
$function$;
revoke all on function private.apply_authoritative_sph(jsonb,jsonb) from public,anon,authenticated,service_role;

create or replace function public.get_sph_status()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $function$
declare v_uid uuid:=(select auth.uid());v_home public.sph_rep_settings%rowtype;v_latest public.sph_presence_events%rowtype;v_access boolean;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501';end if;
  select exists(select 1 from auth.users au join public.app_user_access a on lower(trim(a.email))=lower(trim(au.email)) where au.id=v_uid and a.active) into v_access;
  if not v_access then raise exception 'active_mccoy_access_required' using errcode='42501';end if;
  select * into v_home from public.sph_rep_settings where user_id=v_uid;
  select * into v_latest from public.sph_presence_events where rep_user_id=v_uid and timezone('America/Los_Angeles',event_at)::date=timezone('America/Los_Angeles',clock_timestamp())::date order by event_at desc limit 1;
  return jsonb_build_object('ok',true,'home_configured',v_home.home_latitude is not null,'home_label',v_home.home_label,
    'today',jsonb_build_object('inside_area',v_latest.inside_area,'area_basis',coalesce(v_latest.area_basis,'none'),
      'last_sample_at',v_latest.event_at,'status_label',case when v_latest.id is null then 'Waiting for today''s authenticated workday sample'
       when v_latest.inside_area is true then 'In assigned area · Sales/Hour timer active'
       when v_latest.area_basis='none' then 'No assigned area detected · 11 AM–7 PM fallback applies'
       else 'Outside assigned area' end),
    'policy',jsonb_build_object('source','authenticated_mccoy_workday_area_model','start_in_area_local','13:00',
      'no_area_fallback_local','11:00-19:00','sunday_excluded',true,'lunch_hours',1,'outside_after_7pm_meters',402.336,'outbound_minutes',20));
end;
$function$;
revoke all on function public.get_sph_status() from public,anon;
grant execute on function public.get_sph_status() to authenticated;

-- Replace only the filtered public wrapper. The private verified-sales ranking
-- calculator remains the sole authority for sales totals and tie velocity.
create or replace function public.get_verified_sales_rankings()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth, private
as $function$
declare
  v_requester_email text;v_requester_role text;v_requester_name text;v_ghost_email text;
  v_is_admin boolean:=false;v_is_ghost boolean:=false;v_can_see_ghost_numbers boolean:=false;
  v_result jsonb;v_goals jsonb;v_rankings jsonb;v_sph_map jsonb;v_sph_leader jsonb;
begin
  if (select auth.uid()) is null then raise exception 'authentication_required' using errcode='42501';end if;
  select lower(trim(u.email)) into v_requester_email from auth.users u where u.id=(select auth.uid());
  select lower(trim(a.role)),lower(trim(a.display_name)) into v_requester_role,v_requester_name
  from public.app_user_access a where lower(trim(a.email))=v_requester_email and a.active is true;
  if v_requester_role is null then raise exception 'active_mccoy_access_required' using errcode='42501';end if;
  select lower(trim(s.ghost_email)),jsonb_build_object('day_goal',s.day_goal,'week_goal',s.week_goal,'month_goal',s.month_goal,'year_goal',s.year_goal)
  into v_ghost_email,v_goals from public.ghost_ranking_settings s where s.singleton is true;
  v_is_admin:=v_requester_role='admin';
  v_is_ghost:=v_requester_email=v_ghost_email and v_requester_name='ghost';
  v_can_see_ghost_numbers:=v_is_admin or v_is_ghost;
  v_result:=private.get_verified_sales_rankings_unredacted();

  select coalesce(jsonb_object_agg(lower(trim(m.rep_name))||'|'||lower(trim(m.role))||'|'||lower(trim(coalesce(m.team_name,''))),m.metric),'{}'::jsonb),
    (select x.metric||jsonb_build_object('name',x.rep_name) from private.get_authoritative_sph_metrics() x
      where (x.metric->>'qualified')::boolean and coalesce((x.metric->>'week_sales')::integer,0)>0 order by x.sph_rank limit 1)
  into v_sph_map,v_sph_leader
  from private.get_authoritative_sph_metrics() m;

  select coalesce(jsonb_agg(private.filter_ghost_ranking_numbers(
      private.apply_authoritative_sph(entry.item,v_sph_map),v_can_see_ghost_numbers,v_goals
    ) order by entry.ordinality),'[]'::jsonb)
  into v_rankings from jsonb_array_elements(coalesce(v_result->'rankings','[]'::jsonb)) with ordinality entry(item,ordinality);
  v_result:=jsonb_set(v_result,'{rankings}',v_rankings,true);

  if v_result->'current_rep' is not null then
    v_result:=jsonb_set(v_result,'{current_rep}',private.apply_authoritative_sph(v_result->'current_rep',v_sph_map),true);
    if coalesce((v_result#>>'{current_rep,is_ghost}')::boolean,false) then
      v_result:=jsonb_set(v_result,'{current_rep}',private.filter_ghost_ranking_numbers(v_result->'current_rep',v_can_see_ghost_numbers,v_goals),true);
    end if;
  end if;
  v_result:=jsonb_set(v_result,'{leaders,sales_per_hour}',coalesce(v_sph_leader,'null'::jsonb),true);
  v_result:=jsonb_set(v_result,'{sales_per_hour_policy}',to_jsonb('authenticated_workday_area_model_1pm_in_area_11am_7pm_no_area_one_hour_lunch_sunday_excluded_homeward_or_7pm_quarter_mile_or_20min_outbound_last_sale_close'::text),true);
  v_result:=jsonb_set(v_result,'{ghost_number_visibility}',to_jsonb('admin_and_ghost_only'::text),true);
  return v_result;
end;
$function$;

revoke all on function public.get_verified_sales_rankings() from public,anon;
grant execute on function public.get_verified_sales_rankings() to authenticated,service_role;

update public.app_config set value='2026-08-24-v2',updated_at=clock_timestamp()
where key='privacy_notice_version';

comment on function public.record_sph_presence(text,double precision,double precision,double precision) is
  'Records a server-timestamped, authenticated Sales/Hour workday sample. GPS is classified against explicit assigned areas or assigned geocoded leads and requires current precise-location consent.';
comment on function private.get_authoritative_sph_metrics() is
  'Calculates weekly Sales/Hour from authenticated workday windows, excluding Sundays and one lunch hour per counted day. Start/Stop Knocking is not the time authority.';
