create table if not exists public.sale_admin_review_transactions (
  id bigint generated by default as identity primary key,
  sale_id uuid not null references public.sales_records(id) on delete cascade,
  organization_id uuid not null references public.organizations(id),
  changed_by uuid not null,
  changed_by_email text not null,
  credited_rep_user_id uuid not null,
  credited_rep_email text not null,
  provider_sale_row_id uuid null references public.provider_sales_rows(id),
  reason text not null,
  before_sale jsonb not null,
  after_sale jsonb not null,
  corrections jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sale_admin_review_transactions_sale_idx on public.sale_admin_review_transactions(sale_id, created_at desc);
create index if not exists sale_admin_review_transactions_org_idx on public.sale_admin_review_transactions(organization_id, created_at desc);
alter table public.sale_admin_review_transactions enable row level security;
drop policy if exists sale_admin_review_transactions_admin_read on public.sale_admin_review_transactions;
create policy sale_admin_review_transactions_admin_read on public.sale_admin_review_transactions for select to authenticated using (
  exists (select 1 from auth.users u join public.app_user_access a on lower(a.email)=lower(u.email)
    where u.id=auth.uid() and a.active=true and lower(a.role)='admin' and a.organization_id=sale_admin_review_transactions.organization_id)
);

create or replace function public.admin_review_sale_transaction(
  p_sale_id uuid,
  p_credited_rep_email text,
  p_reason text,
  p_provider_sale_row_id uuid default null,
  p_corrections jsonb default '{}'::jsonb
) returns public.sales_records
language plpgsql security definer
set search_path to 'pg_catalog','public','auth','private'
as $function$
declare
  v_actor uuid:=auth.uid(); v_actor_email text; v_actor_org uuid;
  v_target_id uuid; v_target_email text; v_target_name text;
  v_before public.sales_records%rowtype; v_sale public.sales_records%rowtype; v_provider public.provider_sales_rows%rowtype;
  v_reason text:=trim(coalesce(p_reason,'')); v_corrections jsonb:=coalesce(p_corrections,'{}'::jsonb); v_unknown_keys text[];
  v_customer text; v_provider_first text; v_provider_last text; v_provider_install date; v_provider_order_date date;
  v_new_order text; v_new_account text; v_duplicate uuid;
begin
  if v_actor is null then raise exception 'Authentication required'; end if;
  if v_reason='' then raise exception 'An Admin Sale Review reason is required'; end if;
  select lower(u.email),a.organization_id into v_actor_email,v_actor_org
  from auth.users u join public.app_user_access a on lower(a.email)=lower(u.email)
  where u.id=v_actor and a.active=true and lower(a.role)='admin';
  if v_actor_email is null or v_actor_org is null then raise exception 'Admin access required'; end if;

  select u.id,lower(u.email),coalesce(nullif(trim(a.display_name),''),split_part(u.email,'@',1))
    into v_target_id,v_target_email,v_target_name
  from auth.users u join public.app_user_access a on lower(a.email)=lower(u.email)
  where lower(u.email)=lower(trim(coalesce(p_credited_rep_email,''))) and a.active=true and a.organization_id=v_actor_org limit 1;
  if v_target_id is null then raise exception 'Credited user must have active access in the Admin organization'; end if;

  select * into v_before from public.sales_records where id=p_sale_id and organization_id=v_actor_org for update;
  if not found then raise exception 'Sale not found in Admin organization'; end if;
  if lower(coalesce(v_before.sale_status,''))='not_a_sale' or lower(coalesce(v_before.admin_review_disposition,''))='not_a_sale' then
    raise exception 'Cannot approve a sale locked as NOT A SALE. Restore the Admin review decision first';
  end if;

  select array_agg(k) into v_unknown_keys from jsonb_object_keys(v_corrections) k
  where k not in ('customer_first_name','customer_last_name','customer_phone','customer_email','service_address','provider_order_number','provider_account_number','install_date','order_date','isp','internet_product','internet_speed_mbps','notes');
  if v_unknown_keys is not null then raise exception 'Unsupported correction field(s): %',array_to_string(v_unknown_keys,', '); end if;

  if p_provider_sale_row_id is not null then
    select * into v_provider from public.provider_sales_rows where id=p_provider_sale_row_id and organization_id=v_actor_org for update;
    if not found then raise exception 'Provider evidence not found in Admin organization'; end if;
    if v_provider.admin_evidence_disposition='not_a_sale' or lower(coalesce(v_provider.provider_status,'')) ~ '(abandon|cancel)'
       or lower(coalesce(v_provider.provider_status,'')) !~ '(completed|fulfilled|active|submitted|provider in process)' then
      raise exception 'Selected provider evidence is not eligible sale evidence';
    end if;
    if v_provider.materialized_sale_id is not null and v_provider.materialized_sale_id<>p_sale_id then
      raise exception 'Selected provider evidence is already attached to another sale';
    end if;
    if nullif(trim(coalesce(v_before.isp,'')),'') is not null and nullif(trim(coalesce(v_provider.provider,'')),'') is not null
       and lower(trim(v_before.isp))<>lower(trim(v_provider.provider)) and not (v_corrections ? 'isp') then
      raise exception 'Provider evidence does not match the current sale provider; explicitly correct ISP in the same transaction';
    end if;
    v_customer:=regexp_replace(trim(coalesce(v_provider.customer_name,'')),'\s+',' ','g');
    if position(',' in v_customer)>0 then v_provider_last:=nullif(trim(split_part(v_customer,',',1)),''); v_provider_first:=nullif(trim(split_part(v_customer,',',2)),'');
    else v_provider_first:=nullif(split_part(v_customer,' ',1),''); v_provider_last:=nullif(trim(substr(v_customer,length(coalesce(v_provider_first,''))+1)),''); end if;
    v_provider_install:=coalesce(private.safe_provider_date(v_provider.raw_payload->>'Order Due Date'),private.safe_provider_date(v_provider.raw_payload->>'Due Date'),private.safe_provider_date(v_provider.raw_payload->>'Install Date'),private.safe_provider_date(v_provider.raw_payload->>'Installation'));
    v_provider_order_date:=(v_provider.sale_date at time zone 'America/Los_Angeles')::date;
  end if;

  update public.sales_records s set
    customer_first_name=case when v_corrections ? 'customer_first_name' then trim(coalesce(v_corrections->>'customer_first_name','')) else coalesce(nullif(trim(s.customer_first_name),''),v_provider_first) end,
    customer_last_name=case when v_corrections ? 'customer_last_name' then trim(coalesce(v_corrections->>'customer_last_name','')) else coalesce(nullif(trim(s.customer_last_name),''),v_provider_last) end,
    customer_phone=case when v_corrections ? 'customer_phone' then nullif(trim(v_corrections->>'customer_phone'),'') else s.customer_phone end,
    customer_email=case when v_corrections ? 'customer_email' then nullif(trim(v_corrections->>'customer_email'),'') else s.customer_email end,
    service_address=case when v_corrections ? 'service_address' then trim(coalesce(v_corrections->>'service_address','')) else coalesce(nullif(trim(s.service_address),''),v_provider.service_address) end,
    provider_order_number=case when v_corrections ? 'provider_order_number' then nullif(trim(v_corrections->>'provider_order_number'),'') else coalesce(nullif(trim(s.provider_order_number),''),v_provider.order_number) end,
    provider_account_number=case when v_corrections ? 'provider_account_number' then nullif(trim(v_corrections->>'provider_account_number'),'') else coalesce(nullif(trim(s.provider_account_number),''),v_provider.account_number) end,
    install_date=case when v_corrections ? 'install_date' then nullif(v_corrections->>'install_date','')::date else coalesce(s.install_date,v_provider_install) end,
    order_date=case when v_corrections ? 'order_date' then nullif(v_corrections->>'order_date','')::date else coalesce(s.order_date,v_provider_order_date) end,
    isp=case when v_corrections ? 'isp' then trim(coalesce(v_corrections->>'isp','')) else coalesce(nullif(trim(s.isp),''),v_provider.provider) end,
    internet_product=case when v_corrections ? 'internet_product' then nullif(trim(v_corrections->>'internet_product'),'') else s.internet_product end,
    internet_speed_mbps=case when v_corrections ? 'internet_speed_mbps' then nullif(v_corrections->>'internet_speed_mbps','')::integer else s.internet_speed_mbps end,
    notes=case when v_corrections ? 'notes' then nullif(v_corrections->>'notes','') else s.notes end,
    provider_sale_row_id=coalesce(p_provider_sale_row_id,s.provider_sale_row_id),
    provider_reported_rep_user_id=case when p_provider_sale_row_id is not null then coalesce(s.provider_reported_rep_user_id,v_provider.source_rep_user_id) else s.provider_reported_rep_user_id end,
    provider_reported_rep_email=case when p_provider_sale_row_id is not null then coalesce(s.provider_reported_rep_email,v_provider.seller_email,v_provider.source_rep_email) else s.provider_reported_rep_email end,
    provider_reported_rep_name=case when p_provider_sale_row_id is not null then coalesce(s.provider_reported_rep_name,v_provider.seller_name) else s.provider_reported_rep_name end
  where s.id=p_sale_id returning * into v_sale;

  v_new_order:=nullif(trim(coalesce(v_sale.provider_order_number,'')),''); v_new_account:=nullif(trim(coalesce(v_sale.provider_account_number,'')),'');
  if v_new_order is not null or v_new_account is not null then
    select s.id into v_duplicate from public.sales_records s
    where s.id<>p_sale_id and s.organization_id=v_actor_org and lower(coalesce(s.sale_status,''))<>'not_a_sale'
      and lower(trim(coalesce(s.isp,'')))=lower(trim(coalesce(v_sale.isp,'')))
      and ((v_new_order is not null and private.provider_identity_key(s.provider_order_number)=private.provider_identity_key(v_new_order))
        or (v_new_account is not null and private.provider_identity_key(s.provider_account_number)=private.provider_identity_key(v_new_account))) limit 1;
    if v_duplicate is not null then raise exception 'Correction would duplicate existing sale % by provider order/account identity',v_duplicate; end if;
  end if;

  select * into v_sale from public.sales_records where id=p_sale_id;
  if v_sale.required_metrics_complete is not true then raise exception 'Cannot approve: missing required sale data: %',array_to_string(v_sale.required_metrics_missing,', '); end if;
  if v_sale.rep_user_id is distinct from v_target_id then perform public.admin_reassign_sale_credit(p_sale_id,v_target_id,'Admin Sale Review: '||v_reason); end if;
  select * into v_sale from public.admin_apply_sale_credit(p_sale_id,v_target_email,'Admin Sale Review: '||v_reason);

  if p_provider_sale_row_id is not null then
    update public.provider_sales_rows set materialized_sale_id=p_sale_id,materialization_status='admin_sale_review_verified',materialization_reason='Admin Sale Review attached provider evidence while preserving the explicitly selected credited user.',materialized_at=now(),admin_evidence_disposition=null,admin_evidence_reason=v_reason,admin_evidence_reviewed_by=v_actor,admin_evidence_reviewed_at=now() where id=p_provider_sale_row_id;
    insert into public.provider_sale_evidence_review_history(provider_sale_row_id,sale_id,changed_by,changed_by_email,action,previous_disposition,new_disposition,assigned_rep_user_id,assigned_rep_email,assigned_rep_name,reason)
    values (p_provider_sale_row_id,p_sale_id,v_actor,v_actor_email,'admin_sale_review_approved',v_provider.admin_evidence_disposition,null,v_target_id,v_target_email,v_target_name,v_reason);
  end if;

  update public.sales_records set rep_user_id=v_target_id,rep_email=v_target_email,rep_name=v_target_name,credit_assigned_by=v_actor,credit_assigned_at=now(),credit_assignment_reason='Admin Sale Review authoritative credit: '||v_reason,verification_status='verified_processed',verification_reason='admin_sale_review_verified: '||v_reason,verified_at=coalesce(verified_at,now()),ranking_eligible=true,ranking_verified_at=coalesce(ranking_verified_at,now()),competition_eligible=case when sale_status in ('cancelled','charged_back') then false else true end,
    compensation_snapshot=jsonb_set(jsonb_set(coalesce(compensation_snapshot,'{}'::jsonb),'{admin_sale_review}',jsonb_build_object('authoritative_credited_rep_user_id',v_target_id,'authoritative_credited_rep_email',v_target_email,'provider_sale_row_id',p_provider_sale_row_id,'reviewed_by',v_actor_email,'reviewed_at',now(),'reason',v_reason),true),'{admin_approval}',jsonb_build_object('status','approved','approved_by',v_actor_email,'approved_at',now(),'reason',v_reason),true)
  where id=p_sale_id returning * into v_sale;

  insert into public.sale_admin_review_transactions(sale_id,organization_id,changed_by,changed_by_email,credited_rep_user_id,credited_rep_email,provider_sale_row_id,reason,before_sale,after_sale,corrections)
  values (p_sale_id,v_actor_org,v_actor,v_actor_email,v_target_id,v_target_email,p_provider_sale_row_id,v_reason,to_jsonb(v_before),to_jsonb(v_sale),v_corrections);
  return v_sale;
end;
$function$;

revoke all on function public.admin_review_sale_transaction(uuid,text,text,uuid,jsonb) from public,anon;
grant execute on function public.admin_review_sale_transaction(uuid,text,text,uuid,jsonb) to authenticated;
comment on function public.admin_review_sale_transaction(uuid,text,text,uuid,jsonb) is 'Atomic Admin Sale Review: correct sale/customer data, optionally attach provider evidence, select authoritative credited user, approve verification/rankings, and audit before/after state. Admin-selected credit ownership is authoritative.';
