begin;

create schema if not exists private;

-- Keep import provenance separate from durable lead identity.
create table if not exists public.spotio_import_batches (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  uploaded_by uuid not null,
  uploaded_by_email text not null,
  source_filename text,
  captured_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  record_count integer,
  status text not null default 'received',
  notes text,
  created_at timestamptz not null default now(),
  created_count integer not null default 0,
  updated_count integer not null default 0,
  unchanged_count integer not null default 0,
  collision_count integer not null default 0,
  rejected_count integer not null default 0,
  quarantined_count integer not null default 0,
  archived_count integer not null default 0,
  missing_retained_count integer not null default 0,
  capture_missing_count integer not null default 0,
  normalization_completed_at timestamptz
);

alter table public.spotio_import_batches
  add column if not exists organization_id uuid references public.organizations(id) on delete cascade,
  add column if not exists created_count integer not null default 0,
  add column if not exists updated_count integer not null default 0,
  add column if not exists unchanged_count integer not null default 0,
  add column if not exists collision_count integer not null default 0,
  add column if not exists rejected_count integer not null default 0,
  add column if not exists quarantined_count integer not null default 0,
  add column if not exists archived_count integer not null default 0,
  add column if not exists missing_retained_count integer not null default 0,
  add column if not exists capture_missing_count integer not null default 0,
  add column if not exists normalization_completed_at timestamptz;

create table if not exists public.spotio_import_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.spotio_import_batches(id) on delete cascade,
  chunk_index integer not null,
  item_index integer not null,
  payload jsonb not null,
  created_at timestamptz not null default clock_timestamp(),
  unique (batch_id, chunk_index, item_index)
);

create table if not exists public.spotio_import_results (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  batch_id uuid not null references public.spotio_import_batches(id) on delete cascade,
  item_index integer not null,
  lead_id uuid references public.leads(id) on delete set null,
  action text not null,
  canonical_identity_key text,
  provider_lead_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp(),
  unique (batch_id, item_index)
);

alter table public.spotio_import_results
  drop constraint if exists spotio_import_results_action_check;
alter table public.spotio_import_results
  add constraint spotio_import_results_action_check check (
    action in (
      'created','updated','unchanged','collision','quarantined','missing_retained','archived'
    )
  );

alter table public.leads
  add column if not exists provider_lead_id text,
  add column if not exists canonical_identity_key text,
  add column if not exists fallback_identity_key text,
  add column if not exists import_batch_id uuid references public.spotio_import_batches(id) on delete set null,
  add column if not exists source_stage_id text,
  add column if not exists source_payload jsonb,
  add column if not exists source_first_seen_at timestamptz,
  add column if not exists source_last_seen_at timestamptz,
  add column if not exists source_seen_count integer not null default 1,
  add column if not exists provider text;

create index if not exists spotio_import_batches_org_created_idx
  on public.spotio_import_batches (organization_id, created_at desc, id);
create index if not exists spotio_import_batches_org_status_idx
  on public.spotio_import_batches (organization_id, status, created_at desc);
create index if not exists spotio_import_items_batch_idx
  on public.spotio_import_items (batch_id);
create unique index if not exists spotio_import_items_batch_position_uidx
  on public.spotio_import_items (batch_id, chunk_index, item_index);
create index if not exists spotio_import_results_org_batch_idx
  on public.spotio_import_results (organization_id, batch_id, item_index);
create index if not exists spotio_import_results_lead_idx
  on public.spotio_import_results (lead_id) where lead_id is not null;
create index if not exists idx_leads_import_batch
  on public.leads (import_batch_id);

create or replace function public.mccoy_normalize_lead_identity_part_v1(p_value text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select btrim(regexp_replace(
    lower(regexp_replace(coalesce(p_value, ''), '[^a-zA-Z0-9]+', ' ', 'g')),
    '[[:space:]]+', ' ', 'g'
  ));
$$;

create or replace function private.mccoy_normalized_spotio_street_v1(p_value text)
returns text
language plpgsql
immutable
set search_path = pg_catalog, public
as $$
declare
  v_value text := public.mccoy_normalize_lead_identity_part_v1(p_value);
begin
  v_value := regexp_replace(v_value, '\m(street)\M', 'st', 'g');
  v_value := regexp_replace(v_value, '\m(avenue)\M', 'ave', 'g');
  v_value := regexp_replace(v_value, '\m(road)\M', 'rd', 'g');
  v_value := regexp_replace(v_value, '\m(boulevard)\M', 'blvd', 'g');
  v_value := regexp_replace(v_value, '\m(circle)\M', 'cir', 'g');
  v_value := regexp_replace(v_value, '\m(court)\M', 'ct', 'g');
  v_value := regexp_replace(v_value, '\m(drive)\M', 'dr', 'g');
  v_value := regexp_replace(v_value, '\m(lane)\M', 'ln', 'g');
  v_value := regexp_replace(v_value, '\m(highway)\M', 'hwy', 'g');
  v_value := regexp_replace(v_value, '\m(place)\M', 'pl', 'g');
  v_value := regexp_replace(v_value, '\m(parkway)\M', 'pkwy', 'g');
  v_value := regexp_replace(v_value, '\m(terrace)\M', 'ter', 'g');
  v_value := regexp_replace(v_value, '\m(trail)\M', 'trl', 'g');
  return v_value;
end;
$$;

create or replace function private.mccoy_normalized_spotio_unit_v1(p_value text)
returns text
language plpgsql
immutable
set search_path = pg_catalog, public
as $$
declare
  v_value text := public.mccoy_normalize_lead_identity_part_v1(p_value);
begin
  v_value := regexp_replace(v_value, '\m(apartment|apt|unit|suite|ste)\M', 'unit', 'g');
  return v_value;
end;
$$;

create or replace function private.mccoy_normalized_lead_address(
  p_address1 text,
  p_address2 text,
  p_city text,
  p_state text,
  p_zip text
)
returns text
language plpgsql
immutable
set search_path = pg_catalog, public, private
as $$
declare
  v_street text := private.mccoy_normalized_spotio_street_v1(p_address1);
  v_unit text := private.mccoy_normalized_spotio_unit_v1(p_address2);
  v_city text := public.mccoy_normalize_lead_identity_part_v1(p_city);
  v_state text := upper(regexp_replace(coalesce(p_state, ''), '[^a-zA-Z0-9]+', '', 'g'));
  v_zip text := left(regexp_replace(coalesce(p_zip, ''), '[^0-9]', '', 'g'), 5);
  v_tail text;
begin
  foreach v_tail in array array[
    btrim(concat_ws(' ', nullif(v_city, ''), nullif(lower(v_state), ''), nullif(v_zip, ''))),
    btrim(concat_ws(' ', nullif(v_city, ''), nullif(lower(v_state), '')))
  ] loop
    if v_tail <> '' and v_street like '% ' || v_tail and length(v_street) > length(v_tail) then
      v_street := btrim(left(v_street, length(v_street) - length(v_tail)));
      exit;
    end if;
  end loop;
  return concat_ws('|', v_street, v_unit, v_city, v_state, v_zip);
end;
$$;

-- Production already has normalized_address_key as a stored generated column.
-- Fresh schemas receive the same generated definition. It is never assigned directly.
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'leads'
      and column_name = 'normalized_address_key'
  ) then
    alter table public.leads
      add column normalized_address_key text generated always as (
        private.mccoy_normalized_lead_address(address1,address2,city,state,zip)
      ) stored;
  end if;
end;
$$;

create or replace function private.mccoy_spotio_valid_address(
  p_address1 text,
  p_address2 text,
  p_city text,
  p_state text,
  p_zip text
)
returns boolean
language sql
immutable
set search_path = pg_catalog
as $$
  select btrim(coalesce(p_address1, '')) <> ''
    and btrim(coalesce(p_city, '')) <> ''
    and upper(regexp_replace(coalesce(p_state, ''), '[^a-zA-Z]', '', 'g')) ~ '^[A-Z]{2}$'
    and left(regexp_replace(coalesce(p_zip, ''), '[^0-9]', '', 'g'), 5) ~ '^\d{5}$'
    and lower(btrim(coalesce(p_address1, ''))) not in (
      'prospecting / keep knocking','prospecting keep knocking','hot lead','contacted','smb',
      'follow-up','follow up','no sale made','migrator','existing customer','sale made','admin hold','no sale'
    );
$$;

create or replace function private.mccoy_spotio_fallback_identity_v1(
  p_provider text,
  p_address1 text,
  p_address2 text,
  p_zip text
)
returns text
language plpgsql
immutable
set search_path = pg_catalog, public, private
as $$
declare
  v_provider text := public.mccoy_normalize_lead_identity_part_v1(p_provider);
  v_street text := private.mccoy_normalized_spotio_street_v1(p_address1);
  v_unit text := private.mccoy_normalized_spotio_unit_v1(p_address2);
  v_zip text := left(regexp_replace(coalesce(p_zip, ''), '[^0-9]', '', 'g'), 5);
begin
  if v_street = '' or v_zip !~ '^\d{5}$' then
    return null;
  end if;
  return 'address:' || concat_ws('|', v_provider, v_street, v_unit, v_zip);
end;
$$;

create or replace function private.mccoy_spotio_canonical_identity_v2(
  p_provider_lead_id text,
  p_provider text,
  p_address1 text,
  p_address2 text,
  p_city text,
  p_state text,
  p_zip text
)
returns text
language plpgsql
immutable
set search_path = pg_catalog, private
as $$
declare
  v_provider_id text := regexp_replace(lower(btrim(coalesce(p_provider_lead_id, ''))), '[^a-z0-9:_-]+', '', 'g');
begin
  if v_provider_id <> '' then
    return 'provider:' || v_provider_id;
  end if;
  return private.mccoy_spotio_fallback_identity_v1(p_provider,p_address1,p_address2,p_zip);
end;
$$;

create or replace function private.mccoy_spotio_canonical_identity(
  p_provider_lead_id text,
  p_address1 text,
  p_address2 text,
  p_city text,
  p_state text,
  p_zip text
)
returns text
language sql
immutable
set search_path = pg_catalog, private
as $$
  select private.mccoy_spotio_canonical_identity_v2(
    p_provider_lead_id,null,p_address1,p_address2,p_city,p_state,p_zip
  );
$$;

create or replace function private.set_lead_import_identity_fields()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
begin
  if upper(coalesce(new.source_system, '')) = 'SPOTIO' then
    new.provider_lead_id := nullif(btrim(new.provider_lead_id), '');
    new.provider := nullif(btrim(new.provider), '');
    new.fallback_identity_key := private.mccoy_spotio_fallback_identity_v1(
      new.provider,new.address1,new.address2,new.zip
    );
    new.canonical_identity_key := private.mccoy_spotio_canonical_identity_v2(
      new.provider_lead_id,new.provider,new.address1,new.address2,new.city,new.state,new.zip
    );
    new.source_first_seen_at := coalesce(new.source_first_seen_at,new.created_at,clock_timestamp());
    new.source_last_seen_at := coalesce(new.source_last_seen_at,clock_timestamp());
    new.source_seen_count := greatest(coalesce(new.source_seen_count,1),1);
  end if;
  return new;
end;
$$;

drop trigger if exists set_lead_import_identity_fields on public.leads;
create trigger set_lead_import_identity_fields
before insert or update of
  address1,address2,city,state,zip,source_system,provider,provider_lead_id,
  source_first_seen_at,source_last_seen_at,source_seen_count
on public.leads
for each row execute function private.set_lead_import_identity_fields();

-- Refuse to rewrite identity keys if the permanent rule reveals unresolved collisions.
do $$
declare
  v_collision_groups integer;
  v_fallback_collision_groups integer;
begin
  select count(*) into v_collision_groups
  from (
    select organization_id,proposed_identity
    from (
      select organization_id,
        private.mccoy_spotio_canonical_identity_v2(
          provider_lead_id,provider,address1,address2,city,state,zip
        ) as proposed_identity
      from public.leads
      where deleted_at is null
        and upper(coalesce(source_system, '')) = 'SPOTIO'
    ) proposed
    where proposed_identity is not null
    group by organization_id,proposed_identity
    having count(*) > 1
  ) collisions;

  select count(*) into v_fallback_collision_groups
  from (
    select organization_id,proposed_fallback
    from (
      select organization_id,
        private.mccoy_spotio_fallback_identity_v1(provider,address1,address2,zip) as proposed_fallback
      from public.leads
      where deleted_at is null
        and upper(coalesce(source_system, '')) = 'SPOTIO'
    ) proposed
    where proposed_fallback is not null
    group by organization_id,proposed_fallback
    having count(*) > 1
  ) collisions;

  if v_collision_groups > 0 or v_fallback_collision_groups > 0 then
    raise exception
      'spotio_identity_migration_blocked: % canonical and % fallback collision group(s) require review',
      v_collision_groups,v_fallback_collision_groups;
  end if;
end;
$$;

drop index if exists public.leads_active_spotio_address_uidx;
drop index if exists public.leads_active_spotio_provider_id_uidx;
drop index if exists public.leads_active_spotio_provider_uidx;
drop index if exists public.leads_active_spotio_canonical_uidx;

update public.leads
set fallback_identity_key = private.mccoy_spotio_fallback_identity_v1(provider,address1,address2,zip),
    canonical_identity_key = private.mccoy_spotio_canonical_identity_v2(
      provider_lead_id,provider,address1,address2,city,state,zip
    ),
    source_first_seen_at = coalesce(source_first_seen_at,created_at,clock_timestamp()),
    source_last_seen_at = coalesce(source_last_seen_at,created_at,clock_timestamp()),
    source_seen_count = greatest(coalesce(source_seen_count,1),1)
where upper(coalesce(source_system, '')) = 'SPOTIO';

create unique index leads_active_spotio_provider_uidx
  on public.leads (organization_id,lower(provider_lead_id))
  where deleted_at is null
    and upper(coalesce(source_system, '')) = 'SPOTIO'
    and nullif(btrim(provider_lead_id), '') is not null;
create unique index leads_active_spotio_canonical_uidx
  on public.leads (organization_id,canonical_identity_key)
  where deleted_at is null
    and upper(coalesce(source_system, '')) = 'SPOTIO'
    and canonical_identity_key is not null;
create index if not exists leads_spotio_fallback_lookup_idx
  on public.leads (organization_id,fallback_identity_key,id)
  where deleted_at is null
    and upper(coalesce(source_system, '')) = 'SPOTIO'
    and fallback_identity_key is not null;
create index if not exists leads_active_normalized_address_idx
  on public.leads (normalized_address_key,id)
  where deleted_at is null;

create or replace function public.mccoy_upsert_spotio_lead_v1(
  p_batch_id uuid,
  p_item_index integer,
  p_record jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_batch public.spotio_import_batches%rowtype;
  v_provider_id text := nullif(btrim(coalesce(p_record->>'provider_lead_id','')),'');
  v_provider text := nullif(btrim(coalesce(p_record->>'provider','')),'');
  v_source_stage_id text := nullif(btrim(coalesce(p_record->>'source_stage_id','')),'');
  v_address1 text := btrim(coalesce(p_record->>'address1',''));
  v_address2 text := nullif(btrim(coalesce(p_record->>'address2','')),'');
  v_city text := btrim(coalesce(p_record->>'city',''));
  v_state text := upper(btrim(coalesce(p_record->>'state','')));
  v_zip text := btrim(coalesce(p_record->>'zip',''));
  v_customer_name text := nullif(btrim(coalesce(p_record->>'customer_name','')),'');
  v_phone text := nullif(btrim(coalesce(p_record->>'phone','')),'');
  v_latitude double precision;
  v_longitude double precision;
  v_identity text;
  v_fallback_identity text;
  v_legacy_fallback_identity text;
  v_address_key text;
  v_source_id text;
  v_by_provider public.leads%rowtype;
  v_by_fallback public.leads%rowtype;
  v_archived public.leads%rowtype;
  v_existing public.leads%rowtype;
  v_updated public.leads%rowtype;
  v_fallback_count integer := 0;
  v_action text;
  v_detail jsonb := '{}'::jsonb;
  v_material_change boolean := false;
  v_preserve_coordinates boolean := false;
  v_now timestamptz := clock_timestamp();
  v_result jsonb;
begin
  if p_batch_id is null then
    raise exception 'batch_id_required' using errcode='22023';
  end if;
  if p_item_index is null or p_item_index < 0 then
    raise exception 'valid_item_index_required' using errcode='22023';
  end if;

  select * into v_batch
  from public.spotio_import_batches
  where id = p_batch_id
  for update;
  if not found or v_batch.organization_id is null then
    raise exception 'spotio_batch_not_found_or_unscoped' using errcode='P0002';
  end if;

  if nullif(p_record->>'latitude','') is not null then
    begin
      v_latitude := (p_record->>'latitude')::double precision;
    exception when others then
      v_latitude := null;
    end;
  end if;
  if nullif(p_record->>'longitude','') is not null then
    begin
      v_longitude := (p_record->>'longitude')::double precision;
    exception when others then
      v_longitude := null;
    end;
  end if;
  if v_latitude not between -90 and 90 then v_latitude := null; end if;
  if v_longitude not between -180 and 180 then v_longitude := null; end if;
  if v_latitude is null or v_longitude is null then
    v_latitude := null;
    v_longitude := null;
  end if;

  if not private.mccoy_spotio_valid_address(v_address1,v_address2,v_city,v_state,v_zip) then
    v_action := 'quarantined';
    v_detail := jsonb_build_object(
      'reason','invalid_or_incomplete_service_address',
      'address1',v_address1,'city',v_city,'state',v_state,'zip',v_zip,
      'retained_prior_leads',true
    );
    insert into public.spotio_import_results(
      organization_id,batch_id,item_index,action,provider_lead_id,detail
    ) values (
      v_batch.organization_id,p_batch_id,p_item_index,v_action,v_provider_id,v_detail
    )
    on conflict(batch_id,item_index) do update set
      organization_id=excluded.organization_id,
      lead_id=null,
      action=excluded.action,
      canonical_identity_key=null,
      provider_lead_id=excluded.provider_lead_id,
      detail=excluded.detail,
      created_at=clock_timestamp();
    return jsonb_build_object('ok',true,'action',v_action,'lead_id',null,'detail',v_detail);
  end if;

  v_address_key := private.mccoy_normalized_lead_address(v_address1,v_address2,v_city,v_state,v_zip);
  v_fallback_identity := private.mccoy_spotio_fallback_identity_v1(v_provider,v_address1,v_address2,v_zip);
  v_legacy_fallback_identity := private.mccoy_spotio_fallback_identity_v1(null,v_address1,v_address2,v_zip);
  v_identity := private.mccoy_spotio_canonical_identity_v2(
    v_provider_id,v_provider,v_address1,v_address2,v_city,v_state,v_zip
  );
  v_source_id := 'SPOTIO:'||v_batch.organization_id::text||':'||
    case when v_provider_id is not null
      then 'PROVIDER:'||regexp_replace(lower(v_provider_id),'[^a-z0-9:_-]+','','g')
      else 'ADDRESS:'||md5(v_fallback_identity)
    end;

  if v_provider_id is not null then
    select * into v_by_provider
    from public.leads
    where organization_id=v_batch.organization_id
      and deleted_at is null
      and upper(coalesce(source_system,''))='SPOTIO'
      and lower(provider_lead_id)=lower(v_provider_id)
    order by created_at,id
    limit 1
    for update;
  end if;

  select count(*) into v_fallback_count
  from public.leads
  where organization_id=v_batch.organization_id
    and deleted_at is null
    and upper(coalesce(source_system,''))='SPOTIO'
    and fallback_identity_key=v_fallback_identity;

  if v_fallback_count=1 then
    select * into v_by_fallback
    from public.leads
    where organization_id=v_batch.organization_id
      and deleted_at is null
      and upper(coalesce(source_system,''))='SPOTIO'
      and fallback_identity_key=v_fallback_identity
    order by created_at,id
    limit 1
    for update;
  elsif v_fallback_count=0 and v_provider is not null then
    select count(*) into v_fallback_count
    from public.leads
    where organization_id=v_batch.organization_id
      and deleted_at is null
      and upper(coalesce(source_system,''))='SPOTIO'
      and nullif(btrim(provider),'') is null
      and fallback_identity_key=v_legacy_fallback_identity;

    if v_fallback_count=1 then
      select * into v_by_fallback
      from public.leads
      where organization_id=v_batch.organization_id
        and deleted_at is null
        and upper(coalesce(source_system,''))='SPOTIO'
        and nullif(btrim(provider),'') is null
        and fallback_identity_key=v_legacy_fallback_identity
      order by created_at,id
      limit 1
      for update;
    end if;
  end if;

  if v_fallback_count>1 then
    v_action := 'collision';
    v_detail := jsonb_build_object(
      'reason','fallback_identity_matches_multiple_active_leads',
      'fallback_identity_key',v_fallback_identity,
      'match_count',v_fallback_count,
      'retained_prior_leads',true
    );
  elsif v_by_provider.id is not null
     and v_by_fallback.id is not null
     and v_by_provider.id<>v_by_fallback.id then
    v_action := 'collision';
    v_detail := jsonb_build_object(
      'reason','provider_id_and_fallback_identity_resolve_to_different_active_leads',
      'provider_match_lead_id',v_by_provider.id,
      'fallback_match_lead_id',v_by_fallback.id,
      'retained_prior_leads',true
    );
  end if;

  if v_action='collision' then
    insert into public.spotio_import_results(
      organization_id,batch_id,item_index,action,canonical_identity_key,provider_lead_id,detail
    ) values (
      v_batch.organization_id,p_batch_id,p_item_index,v_action,v_identity,v_provider_id,v_detail
    )
    on conflict(batch_id,item_index) do update set
      organization_id=excluded.organization_id,
      lead_id=null,
      action=excluded.action,
      canonical_identity_key=excluded.canonical_identity_key,
      provider_lead_id=excluded.provider_lead_id,
      detail=excluded.detail,
      created_at=clock_timestamp();
    return jsonb_build_object('ok',true,'action',v_action,'lead_id',null,'detail',v_detail);
  end if;

  if v_by_provider.id is not null then
    v_existing := v_by_provider;
  else
    v_existing := v_by_fallback;
  end if;

  if v_existing.id is null then
    select * into v_archived
    from public.leads
    where organization_id=v_batch.organization_id
      and deleted_at is not null
      and upper(coalesce(source_system,''))='SPOTIO'
      and (
        (v_provider_id is not null and lower(coalesce(provider_lead_id,''))=lower(v_provider_id))
        or fallback_identity_key=v_fallback_identity
        or (v_provider is not null and nullif(btrim(provider),'') is null
            and fallback_identity_key=v_legacy_fallback_identity)
      )
    order by deleted_at desc,created_at,id
    limit 1;

    if v_archived.duplicate_of_lead_id is not null then
      select * into v_existing
      from public.leads
      where id=v_archived.duplicate_of_lead_id
        and organization_id=v_batch.organization_id
        and deleted_at is null
      for update;
    elsif v_archived.id is not null and v_archived.deletion_reason='manual' then
      v_action := 'archived';
      v_detail := jsonb_build_object(
        'reason','explicitly_archived_lead_retained',
        'archived_lead_id',v_archived.id,
        'retained_prior_leads',true
      );
      insert into public.spotio_import_results(
        organization_id,batch_id,item_index,lead_id,action,canonical_identity_key,provider_lead_id,detail
      ) values (
        v_batch.organization_id,p_batch_id,p_item_index,v_archived.id,v_action,v_identity,v_provider_id,v_detail
      )
      on conflict(batch_id,item_index) do update set
        organization_id=excluded.organization_id,
        lead_id=excluded.lead_id,
        action=excluded.action,
        canonical_identity_key=excluded.canonical_identity_key,
        provider_lead_id=excluded.provider_lead_id,
        detail=excluded.detail,
        created_at=clock_timestamp();
      return jsonb_build_object('ok',true,'action',v_action,'lead_id',v_archived.id,'detail',v_detail);
    end if;
  end if;

  if v_existing.id is null then
    insert into public.leads(
      organization_id,source_system,source_id,provider,provider_lead_id,
      canonical_identity_key,fallback_identity_key,
      import_batch_id,source_stage_id,source_payload,
      address1,address2,city,state,zip,latitude,longitude,
      customer_name,phone,current_disposition,stage,pin_color,pin_color_source,
      source_first_seen_at,source_last_seen_at,source_seen_count
    ) values (
      v_batch.organization_id,'SPOTIO',v_source_id,v_provider,v_provider_id,
      v_identity,v_fallback_identity,
      p_batch_id,v_source_stage_id,coalesce(p_record->'source_payload',p_record),
      v_address1,v_address2,v_city,v_state,v_zip,v_latitude,v_longitude,
      v_customer_name,v_phone,'uncontacted','Prospecting','#fbbf24','stage',
      v_now,v_now,1
    )
    returning * into v_updated;

    v_action := 'created';
    v_detail := jsonb_build_object(
      'classification','new_lead',
      'assignment_preserved',true,
      'disposition_preserved',true,
      'verified_coordinates_preserved',null,
      'retained_prior_leads',true
    );
  else
    v_preserve_coordinates :=
      coalesce(v_existing.geocode_verification_status,'') in (
        'manual_door_verified','google_verified_preserved','google_address_validation_applied'
      )
      or coalesce(v_existing.geocode_status,'') in (
        'manual','field_verified','google_rooftop','google_address_validation'
      );

    v_material_change :=
      v_existing.address1 is distinct from v_address1
      or v_existing.address2 is distinct from v_address2
      or v_existing.city is distinct from v_city
      or v_existing.state is distinct from v_state
      or v_existing.zip is distinct from v_zip
      or (v_provider is not null and v_existing.provider is distinct from v_provider)
      or (v_customer_name is not null and v_existing.customer_name is distinct from v_customer_name)
      or (v_phone is not null and v_existing.phone is distinct from v_phone)
      or (v_provider_id is not null and v_existing.provider_lead_id is distinct from v_provider_id)
      or v_existing.source_stage_id is distinct from v_source_stage_id
      or (
        not v_preserve_coordinates
        and v_latitude is not null
        and (
          v_existing.latitude is distinct from v_latitude
          or v_existing.longitude is distinct from v_longitude
        )
      );

    update public.leads
    set source_system='SPOTIO',
        source_id=v_source_id,
        provider=coalesce(v_provider,provider),
        provider_lead_id=coalesce(v_provider_id,provider_lead_id),
        canonical_identity_key=v_identity,
        fallback_identity_key=v_fallback_identity,
        import_batch_id=p_batch_id,
        source_stage_id=coalesce(v_source_stage_id,source_stage_id),
        source_payload=coalesce(p_record->'source_payload',p_record),
        address1=v_address1,
        address2=v_address2,
        city=v_city,
        state=v_state,
        zip=v_zip,
        latitude=case when v_preserve_coordinates or v_latitude is null then latitude else v_latitude end,
        longitude=case when v_preserve_coordinates or v_latitude is null then longitude else v_longitude end,
        geocode_status=case
          when v_preserve_coordinates or v_latitude is null then geocode_status
          else coalesce(geocode_status,'spotio_source')
        end,
        geocode_provider=case
          when v_preserve_coordinates or v_latitude is null then geocode_provider
          else coalesce(geocode_provider,'spotio')
        end,
        geocode_verification_status=case
          when v_preserve_coordinates or v_latitude is null then geocode_verification_status
          else coalesce(geocode_verification_status,'unverified_source')
        end,
        customer_name=coalesce(v_customer_name,customer_name),
        phone=coalesce(v_phone,phone),
        source_first_seen_at=coalesce(source_first_seen_at,created_at,v_now),
        source_last_seen_at=v_now,
        source_seen_count=greatest(coalesce(source_seen_count,1),1)+1
    where id=v_existing.id
    returning * into v_updated;

    v_action := case when v_material_change then 'updated' else 'unchanged' end;
    v_detail := jsonb_build_object(
      'classification',case when v_material_change then 'existing_lead_updated' else 'existing_lead_unchanged' end,
      'assignment_preserved',
        v_updated.assigned_rep_id is not distinct from v_existing.assigned_rep_id
        and v_updated.assigned_manager_id is not distinct from v_existing.assigned_manager_id
        and v_updated.assigned_admin_email is not distinct from v_existing.assigned_admin_email,
      'disposition_preserved',
        v_updated.current_disposition is not distinct from v_existing.current_disposition
        and v_updated.stage is not distinct from v_existing.stage
        and v_updated.last_activity_type is not distinct from v_existing.last_activity_type
        and v_updated.visit_result is not distinct from v_existing.visit_result,
      'verified_coordinates_preserved',
        not v_preserve_coordinates
        or (
          v_updated.latitude is not distinct from v_existing.latitude
          and v_updated.longitude is not distinct from v_existing.longitude
        ),
      'retained_prior_leads',true
    );
  end if;

  insert into public.spotio_import_results(
    organization_id,batch_id,item_index,lead_id,action,canonical_identity_key,provider_lead_id,detail
  ) values (
    v_batch.organization_id,p_batch_id,p_item_index,v_updated.id,v_action,v_identity,v_provider_id,v_detail
  )
  on conflict(batch_id,item_index) do update set
    organization_id=excluded.organization_id,
    lead_id=excluded.lead_id,
    action=excluded.action,
    canonical_identity_key=excluded.canonical_identity_key,
    provider_lead_id=excluded.provider_lead_id,
    detail=excluded.detail,
    created_at=clock_timestamp();

  v_result := jsonb_build_object(
    'ok',true,
    'action',v_action,
    'lead_id',v_updated.id,
    'provider_lead_id',v_provider_id,
    'canonical_identity_key',v_identity,
    'fallback_identity_key',v_fallback_identity,
    'normalized_address_key',v_address_key
  ) || v_detail;
  return v_result;
exception
  when unique_violation then
    v_detail := jsonb_build_object(
      'classification','possible_collision_requiring_review',
      'reason','active_identity_changed_during_import',
      'retained_prior_leads',true
    );
    insert into public.spotio_import_results(
      organization_id,batch_id,item_index,action,canonical_identity_key,provider_lead_id,detail
    ) values (
      v_batch.organization_id,p_batch_id,p_item_index,'collision',v_identity,v_provider_id,v_detail
    )
    on conflict(batch_id,item_index) do update set
      organization_id=excluded.organization_id,
      lead_id=null,
      action=excluded.action,
      canonical_identity_key=excluded.canonical_identity_key,
      provider_lead_id=excluded.provider_lead_id,
      detail=excluded.detail,
      created_at=clock_timestamp();
    return jsonb_build_object(
      'ok',true,'action','collision','lead_id',null,
      'provider_lead_id',v_provider_id,
      'canonical_identity_key',v_identity,
      'detail',v_detail
    );
end;
$$;

create or replace function public.mccoy_upsert_spotio_batch_v1(
  p_batch_id uuid,
  p_records jsonb,
  p_item_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record jsonb;
  v_result jsonb;
  v_index integer := 0;
  v_created integer := 0;
  v_updated integer := 0;
  v_unchanged integer := 0;
  v_collision integer := 0;
  v_quarantined integer := 0;
  v_archived integer := 0;
begin
  if jsonb_typeof(p_records) <> 'array' then
    raise exception 'records_array_required' using errcode='22023';
  end if;

  for v_record in select value from jsonb_array_elements(p_records)
  loop
    v_result := public.mccoy_upsert_spotio_lead_v1(
      p_batch_id,greatest(coalesce(p_item_offset,0),0)+v_index,v_record
    );
    case v_result->>'action'
      when 'created' then v_created := v_created + 1;
      when 'updated' then v_updated := v_updated + 1;
      when 'unchanged' then v_unchanged := v_unchanged + 1;
      when 'collision' then v_collision := v_collision + 1;
      when 'quarantined' then v_quarantined := v_quarantined + 1;
      when 'archived' then v_archived := v_archived + 1;
      else v_collision := v_collision + 1;
    end case;
    v_index := v_index + 1;
  end loop;

  update public.spotio_import_batches
  set created_count=created_count+v_created,
      updated_count=updated_count+v_updated,
      unchanged_count=unchanged_count+v_unchanged,
      collision_count=collision_count+v_collision,
      quarantined_count=quarantined_count+v_quarantined,
      archived_count=archived_count+v_archived
  where id=p_batch_id;

  return jsonb_build_object(
    'ok',true,
    'processed',v_index,
    'created',v_created,
    'updated',v_updated,
    'unchanged',v_unchanged,
    'collisions',v_collision,
    'quarantined',v_quarantined,
    'archived',v_archived,
    'retention_mode','additive_missing_retained',
    'import_batch_is_provenance_only',true
  );
end;
$$;

create or replace function public.mccoy_classify_spotio_missing_retained_v1(
  p_batch_id uuid,
  p_item_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_batch public.spotio_import_batches%rowtype;
  v_inserted integer := 0;
begin
  select * into v_batch
  from public.spotio_import_batches
  where id=p_batch_id
  for update;
  if not found or v_batch.organization_id is null then
    raise exception 'spotio_batch_not_found_or_unscoped' using errcode='P0002';
  end if;

  delete from public.spotio_import_results
  where batch_id=p_batch_id and action='missing_retained';

  with missing as (
    select
      l.id as lead_id,
      l.canonical_identity_key,
      l.provider_lead_id,
      row_number() over(order by l.id)-1 as position
    from public.leads l
    where l.organization_id=v_batch.organization_id
      and l.deleted_at is null
      and upper(coalesce(l.source_system,''))='SPOTIO'
      and not exists (
        select 1
        from public.spotio_import_results r
        where r.batch_id=p_batch_id
          and r.lead_id=l.id
          and r.action in ('created','updated','unchanged')
      )
  ), inserted as (
    insert into public.spotio_import_results(
      organization_id,batch_id,item_index,lead_id,action,canonical_identity_key,provider_lead_id,detail
    )
    select
      v_batch.organization_id,
      p_batch_id,
      greatest(coalesce(p_item_offset,0),0)+position::integer,
      lead_id,
      'missing_retained',
      canonical_identity_key,
      provider_lead_id,
      jsonb_build_object(
        'classification','missing_from_upload_but_retained',
        'reason','absent_from_upload_retained',
        'retained_prior_leads',true
      )
    from missing
    on conflict(batch_id,item_index) do update set
      organization_id=excluded.organization_id,
      lead_id=excluded.lead_id,
      action=excluded.action,
      canonical_identity_key=excluded.canonical_identity_key,
      provider_lead_id=excluded.provider_lead_id,
      detail=excluded.detail,
      created_at=clock_timestamp()
    returning 1
  )
  select count(*) into v_inserted from inserted;

  update public.spotio_import_batches
  set missing_retained_count=v_inserted
  where id=p_batch_id;

  return jsonb_build_object(
    'ok',true,
    'missing_retained',v_inserted,
    'retention_mode','additive_missing_retained',
    'import_batch_is_provenance_only',true
  );
end;
$$;

revoke all on function public.mccoy_upsert_spotio_lead_v1(uuid,integer,jsonb) from public,anon,authenticated;
revoke all on function public.mccoy_upsert_spotio_batch_v1(uuid,jsonb,integer) from public,anon,authenticated;
revoke all on function public.mccoy_classify_spotio_missing_retained_v1(uuid,integer) from public,anon,authenticated;
grant execute on function public.mccoy_upsert_spotio_lead_v1(uuid,integer,jsonb) to service_role;
grant execute on function public.mccoy_upsert_spotio_batch_v1(uuid,jsonb,integer) to service_role;
grant execute on function public.mccoy_classify_spotio_missing_retained_v1(uuid,integer) to service_role;

grant select,insert,update,delete on public.spotio_import_batches to service_role;
grant select,insert,update,delete on public.spotio_import_items to service_role;
grant select,insert,update,delete on public.spotio_import_results to service_role;
grant usage,select on all sequences in schema public to service_role;

alter table public.spotio_import_batches enable row level security;
alter table public.spotio_import_items enable row level security;
alter table public.spotio_import_results enable row level security;

commit;
