alter table public.manager_override_controls rename to manager_override_controls_legacy_20260820;

create table public.manager_override_controls (
  manager_email text primary key,
  manager_name text not null,
  overrides_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

insert into public.manager_override_controls (manager_email,manager_name,overrides_enabled,updated_at,updated_by)
select distinct on (lower(a.email))
  lower(a.email),
  coalesce(nullif(trim(a.display_name),''),lower(a.email)),
  c.overrides_enabled,
  c.updated_at,
  c.updated_by
from public.app_user_access a
join public.manager_override_controls_legacy_20260820 c
  on lower(coalesce(c.manager_email,''))=lower(a.email)
  or (c.manager_email is null and c.manager_name=a.display_name)
where a.active=true and a.role in ('manager','admin')
order by lower(a.email),
  case when lower(coalesce(c.manager_email,''))=lower(a.email) then 0 else 1 end,
  c.updated_at desc;

alter table public.manager_override_controls enable row level security;
create index manager_override_controls_name_idx on public.manager_override_controls (manager_name);

create table if not exists public.manager_override_authority_changes (
  id bigint generated by default as identity primary key,
  changed_at timestamptz not null default now(),
  changed_by uuid not null,
  changed_by_email text not null,
  manager_email text not null,
  manager_name text not null,
  previous_enabled boolean not null,
  new_enabled boolean not null
);

create index if not exists manager_override_authority_changes_manager_idx
  on public.manager_override_authority_changes (manager_email,changed_at desc);

alter table public.manager_override_authority_changes enable row level security;

create or replace function public.admin_set_manager_override_authority(
  p_manager_email text,
  p_enabled boolean,
  p_changed_by uuid,
  p_changed_by_email text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_email text := lower(trim(p_manager_email));
  v_name text;
  v_previous boolean := true;
  v_had_control boolean := false;
  v_changed boolean;
begin
  select coalesce(nullif(trim(display_name),''),email) into v_name
  from public.app_user_access
  where lower(email)=v_email and active=true and role in ('manager','admin');
  if not found then raise exception 'active_manager_required'; end if;

  select overrides_enabled into v_previous
  from public.manager_override_controls where manager_email=v_email;
  v_had_control := found;
  if not v_had_control then v_previous := true; end if;
  v_changed := v_previous is distinct from p_enabled;

  insert into public.manager_override_controls (
    manager_email,manager_name,overrides_enabled,updated_at,updated_by
  ) values (v_email,v_name,p_enabled,now(),p_changed_by)
  on conflict (manager_email) do update set
    manager_name=excluded.manager_name,
    overrides_enabled=excluded.overrides_enabled,
    updated_at=excluded.updated_at,
    updated_by=excluded.updated_by;

  if v_changed then
    insert into public.manager_override_authority_changes (
      changed_by,changed_by_email,manager_email,manager_name,previous_enabled,new_enabled
    ) values (
      p_changed_by,lower(trim(p_changed_by_email)),v_email,v_name,v_previous,p_enabled
    );
  end if;

  return jsonb_build_object(
    'changed',v_changed,'manager_email',v_email,'manager_name',v_name,
    'previous_enabled',v_previous,'overrides_enabled',p_enabled
  );
end;
$$;

revoke all on function public.admin_set_manager_override_authority(text,boolean,uuid,text) from public,anon,authenticated;
grant execute on function public.admin_set_manager_override_authority(text,boolean,uuid,text) to service_role;
