create table if not exists public.accounting_file_deliveries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  created_by uuid not null,
  created_by_email text not null,
  delivery_method text not null check (delivery_method in ('download','email','onedrive')),
  recipient_email text,
  rep_email text,
  period_start timestamptz,
  period_end timestamptz,
  file_name text not null,
  storage_path text not null,
  content_sha256 text not null,
  record_count integer not null check (record_count >= 0),
  status text not null check (status in ('prepared','sent','uploaded','failed')),
  external_id text,
  shared_url text,
  error_code text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists accounting_file_deliveries_created_at_idx
  on public.accounting_file_deliveries (created_at desc);
create index if not exists accounting_file_deliveries_rep_email_idx
  on public.accounting_file_deliveries (rep_email, created_at desc);

alter table public.accounting_file_deliveries enable row level security;

create table if not exists public.customer_list_access_log (
  id bigint generated by default as identity primary key,
  accessed_at timestamptz not null default now(),
  user_id uuid not null,
  user_email text not null,
  record_count integer not null check (record_count >= 0),
  filters jsonb not null default '{}'::jsonb
);

create index if not exists customer_list_access_log_user_idx
  on public.customer_list_access_log (user_id, accessed_at desc);

alter table public.customer_list_access_log enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('accounting-records', 'accounting-records', false, 10485760, array['text/csv'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
