begin;

alter table public.leads
  add column if not exists notes text not null default '',
  add column if not exists contact_updated_at timestamptz,
  add column if not exists contact_updated_by uuid,
  add column if not exists contact_updated_by_email text,
  add column if not exists created_by_user_id uuid,
  add column if not exists created_by_email text;

create table if not exists public.lead_contact_edit_history (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  lead_id uuid not null references public.leads(id) on delete cascade,
  actor_user_id uuid not null,
  actor_email text not null,
  actor_role text not null,
  action text not null,
  previous_values jsonb not null default '{}'::jsonb,
  incoming_values jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp(),
  constraint lead_contact_edit_history_action_check check (
    action in ('update_contact','create_field_lead','matched_existing_address')
  )
);

create index if not exists lead_contact_edit_history_lead_created_idx
  on public.lead_contact_edit_history (lead_id, created_at desc, id desc);
create index if not exists lead_contact_edit_history_actor_created_idx
  on public.lead_contact_edit_history (actor_user_id, created_at desc, id desc);
create index if not exists leads_created_by_user_active_idx
  on public.leads (created_by_user_id, created_at desc, id)
  where deleted_at is null and created_by_user_id is not null;

alter table public.lead_contact_edit_history enable row level security;
revoke all on public.lead_contact_edit_history from public, anon, authenticated;
grant select, insert, update, delete on public.lead_contact_edit_history to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on column public.leads.notes is
  'Shared field notes editable by any active McCoy field-role user in the same organization through the audited lead-field-actions function.';
comment on table public.lead_contact_edit_history is
  'Immutable audit trail for organization-scoped lead customer-name, phone, notes, and field-created address changes.';

commit;
