-- Preview-only security hardening for Live Feed comments.
-- Free-form comments remain quarantined until an Admin explicitly reviews and
-- approves them. Only approved comments become organization-wide Realtime events.

alter table public.live_feed_comments
  add column if not exists moderation_status text not null default 'pending',
  add column if not exists published_at timestamptz,
  add column if not exists moderated_at timestamptz,
  add column if not exists moderated_by_user_id uuid,
  add column if not exists moderation_reason text;

alter table public.live_feed_comments
  drop constraint if exists live_feed_comments_moderation_status,
  drop constraint if exists live_feed_comments_moderation_state;

alter table public.live_feed_comments
  add constraint live_feed_comments_moderation_status
    check (moderation_status in ('pending','approved','rejected')),
  add constraint live_feed_comments_moderation_state
    check (
      (
        moderation_status = 'pending'
        and published_at is null
        and moderated_at is null
        and moderated_by_user_id is null
      )
      or (
        moderation_status = 'approved'
        and published_at is not null
        and moderated_at is not null
        and moderated_by_user_id is not null
      )
      or (
        moderation_status = 'rejected'
        and published_at is null
        and moderated_at is not null
        and moderated_by_user_id is not null
      )
    );

comment on column public.live_feed_comments.moderation_status is
  'Fail-closed publication state. Free-form comments are pending until an Admin approves or rejects them.';
comment on column public.live_feed_comments.published_at is
  'Organization-wide publication timestamp. NULL until Admin approval.';

create index if not exists live_feed_comments_org_approved_published_idx
  on public.live_feed_comments(organization_id, published_at desc, id desc)
  where deleted_at is null and moderation_status = 'approved';
create index if not exists live_feed_comments_org_pending_created_idx
  on public.live_feed_comments(organization_id, created_at desc, id desc)
  where deleted_at is null and moderation_status = 'pending';

-- Approved comments are visible to all active organization members. Pending
-- comments are visible only to their author and organization Admins. This also
-- keeps pending bodies out of Realtime delivery to ordinary members.
drop policy if exists "active organization members read live feed comments" on public.live_feed_comments;
create policy "active organization members read live feed comments"
on public.live_feed_comments
for select
to authenticated
using (
  organization_id = private.current_organization_id()
  and private.organization_access_allowed(organization_id, 'field_coach_access')
  and exists (
    select 1
    from public.organization_memberships membership
    join public.app_user_access access
      on access.organization_id = membership.organization_id
     and lower(access.email) = lower(membership.email)
    where membership.organization_id = live_feed_comments.organization_id
      and membership.auth_user_id = auth.uid()
      and membership.active
      and access.active
  )
  and (
    moderation_status = 'approved'
    or author_user_id = auth.uid()
    or exists (
      select 1
      from public.organization_memberships admin_membership
      join public.app_user_access admin_access
        on admin_access.organization_id = admin_membership.organization_id
       and lower(admin_access.email) = lower(admin_membership.email)
      where admin_membership.organization_id = live_feed_comments.organization_id
        and admin_membership.auth_user_id = auth.uid()
        and admin_membership.active
        and admin_access.active
        and lower(admin_access.role) = 'admin'
    )
  )
);

create table if not exists private.live_feed_comment_moderation_events (
  id bigint generated by default as identity primary key,
  comment_id uuid not null,
  organization_id uuid not null,
  decision text not null,
  original_body text not null,
  moderated_at timestamptz not null,
  moderated_by_user_id uuid not null,
  moderated_by_email text not null,
  reason text not null,
  constraint live_feed_comment_moderation_decision
    check (decision in ('approved','rejected')),
  constraint live_feed_comment_moderation_reason_present
    check (char_length(btrim(reason)) between 3 and 240)
);

create unique index if not exists live_feed_comment_moderation_once
  on private.live_feed_comment_moderation_events(comment_id);
revoke all on table private.live_feed_comment_moderation_events from public, anon, authenticated;
grant select, insert on table private.live_feed_comment_moderation_events to service_role;

create or replace function public.post_live_feed_comment_v1(
  p_body text,
  p_client_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private, auth
as $$
declare
  v_actor record;
  v_body text;
  v_block_reason text;
  v_existing public.live_feed_comments%rowtype;
  v_comment public.live_feed_comments%rowtype;
  v_now timestamptz := statement_timestamp();
begin
  select * into v_actor from private.live_feed_actor_context();

  if p_client_request_id is null then
    raise exception 'client_request_id_required' using errcode = '22023';
  end if;

  v_body := replace(replace(btrim(coalesce(p_body, '')), E'\r\n', E'\n'), E'\r', E'\n');
  v_body := regexp_replace(v_body, '[[:blank:]]+', ' ', 'g');
  v_body := regexp_replace(v_body, E'\n{3,}', E'\n\n', 'g');
  if char_length(v_body) < 1 then
    raise exception 'comment_required' using errcode = '22023';
  end if;
  if char_length(v_body) > 280 then
    raise exception 'comment_too_long' using errcode = '22023';
  end if;

  v_block_reason := private.live_feed_comment_prohibited_reason(v_body);
  if v_block_reason is not null then
    raise exception 'customer_information_not_allowed:%', v_block_reason using errcode = '22023';
  end if;

  -- Catch the explicit disclosure form called out by security review. Less
  -- obvious free-form text remains quarantined until human Admin approval.
  if v_body ~ E'\\m(Customer|Subscriber|Homeowner)\\M[[:space:]:#-]+[[:upper:]][[:alpha:]''-]+[[:space:]]+[[:upper:]][[:alpha:]''-]+' then
    raise exception 'customer_information_not_allowed:customer_name_context' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_actor.auth_user_id::text, 20260903));

  select * into v_existing
  from public.live_feed_comments
  where author_user_id = v_actor.auth_user_id
    and organization_id = v_actor.organization_id
    and client_request_id = p_client_request_id;

  if found then
    if v_existing.deleted_at is not null then
      raise exception 'comment_request_already_deleted' using errcode = '23505';
    end if;
    if v_existing.body is distinct from v_body then
      raise exception 'client_request_id_reused' using errcode = '23505';
    end if;
    return jsonb_build_object(
      'ok', true,
      'idempotent', true,
      'requires_moderation', v_existing.moderation_status = 'pending',
      'event', jsonb_build_object(
        'event_id', 'comment:' || v_existing.id::text,
        'event_type', 'comment',
        'comment_id', v_existing.id,
        'created_at', coalesce(v_existing.published_at, v_existing.created_at),
        'submitted_at', v_existing.created_at,
        'published_at', v_existing.published_at,
        'moderation_status', v_existing.moderation_status,
        'actor_user_id', v_existing.author_user_id,
        'actor_name', v_existing.author_display_name,
        'actor_role', v_existing.author_role,
        'message', v_existing.body,
        'secondary_messages', '[]'::jsonb,
        'scope', v_existing.scope,
        'is_own', true,
        'can_delete', v_actor.role = 'admin' or v_existing.created_at >= v_now - interval '5 minutes',
        'can_moderate', v_actor.role = 'admin' and v_existing.moderation_status = 'pending',
        'delete_deadline', v_existing.created_at + interval '5 minutes'
      )
    );
  end if;

  if exists (
    select 1 from public.live_feed_comments
    where organization_id = v_actor.organization_id
      and author_user_id = v_actor.auth_user_id
      and created_at > v_now - interval '3 seconds'
  ) then
    raise exception 'comment_rate_limited_3_seconds' using errcode = 'P0001';
  end if;

  if (
    select count(*) from public.live_feed_comments
    where organization_id = v_actor.organization_id
      and author_user_id = v_actor.auth_user_id
      and created_at > v_now - interval '1 minute'
  ) >= 5 then
    raise exception 'comment_rate_limited_5_per_minute' using errcode = 'P0001';
  end if;

  if (
    select count(*) from public.live_feed_comments
    where organization_id = v_actor.organization_id
      and author_user_id = v_actor.auth_user_id
      and created_at > v_now - interval '1 hour'
  ) >= 30 then
    raise exception 'comment_rate_limited_30_per_hour' using errcode = 'P0001';
  end if;

  insert into public.live_feed_comments (
    organization_id,
    author_user_id,
    author_display_name,
    author_role,
    scope,
    scope_id,
    body,
    client_request_id,
    moderation_status,
    created_at
  ) values (
    v_actor.organization_id,
    v_actor.auth_user_id,
    v_actor.display_name,
    v_actor.role,
    'organization',
    null,
    v_body,
    p_client_request_id,
    'pending',
    v_now
  )
  returning * into v_comment;

  return jsonb_build_object(
    'ok', true,
    'idempotent', false,
    'requires_moderation', true,
    'event', jsonb_build_object(
      'event_id', 'comment:' || v_comment.id::text,
      'event_type', 'comment',
      'comment_id', v_comment.id,
      'created_at', v_comment.created_at,
      'submitted_at', v_comment.created_at,
      'published_at', null,
      'moderation_status', 'pending',
      'actor_user_id', v_comment.author_user_id,
      'actor_name', v_comment.author_display_name,
      'actor_role', v_comment.author_role,
      'message', v_comment.body,
      'secondary_messages', '[]'::jsonb,
      'scope', v_comment.scope,
      'is_own', true,
      'can_delete', true,
      'can_moderate', v_actor.role = 'admin',
      'delete_deadline', v_comment.created_at + interval '5 minutes'
    )
  );
end;
$$;

revoke all on function public.post_live_feed_comment_v1(text, uuid) from public, anon;
grant execute on function public.post_live_feed_comment_v1(text, uuid) to authenticated;

create or replace function public.get_live_feed_v1(
  p_limit integer default 100,
  p_before timestamptz default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private, auth
as $$
declare
  v_actor record;
  v_limit integer := greatest(1, least(coalesce(p_limit, 100), 100));
  v_now timestamptz := statement_timestamp();
  v_cutoff timestamptz := statement_timestamp() - interval '30 days';
  v_events jsonb;
begin
  select * into v_actor from private.live_feed_actor_context();

  with sale_events as (
    select
      feed.created_at as event_at,
      'sale:' || feed.id::text as event_id,
      jsonb_build_object(
        'event_id', 'sale:' || feed.id::text,
        'event_type', 'sale',
        'created_at', feed.created_at,
        'submitted_at', feed.created_at,
        'published_at', feed.created_at,
        'moderation_status', null,
        'actor_user_id', feed.rep_user_id,
        'actor_name', feed.rep_name,
        'actor_role', null,
        'message', feed.message,
        'secondary_messages', coalesce((
          select jsonb_agg(message.value order by message.ordinality)
          from jsonb_array_elements_text(
            case
              when jsonb_typeof(feed.celebration_messages) = 'array' then feed.celebration_messages
              else '[]'::jsonb
            end
          ) with ordinality as message(value, ordinality)
          where btrim(message.value) <> ''
            and btrim(message.value) <> btrim(feed.message)
        ), '[]'::jsonb),
        'related_sale_id', feed.sale_id,
        'celebration_types', to_jsonb(feed.celebration_types),
        'scope', 'organization',
        'is_own', false,
        'can_delete', false,
        'can_moderate', false,
        'delete_deadline', null
      ) as event
    from public.sales_feed feed
    where feed.organization_id = v_actor.organization_id
      and feed.ranking_eligible_at_event
      and feed.created_at >= v_cutoff
      and feed.created_at < coalesce(p_before, 'infinity'::timestamptz)
  ), comment_events as (
    select
      coalesce(comment.published_at, comment.created_at) as event_at,
      'comment:' || comment.id::text as event_id,
      jsonb_build_object(
        'event_id', 'comment:' || comment.id::text,
        'event_type', 'comment',
        'comment_id', comment.id,
        'created_at', coalesce(comment.published_at, comment.created_at),
        'submitted_at', comment.created_at,
        'published_at', comment.published_at,
        'moderation_status', comment.moderation_status,
        'actor_user_id', comment.author_user_id,
        'actor_name', comment.author_display_name,
        'actor_role', comment.author_role,
        'message', comment.body,
        'secondary_messages', '[]'::jsonb,
        'related_sale_id', null,
        'scope', comment.scope,
        'is_own', comment.author_user_id = v_actor.auth_user_id,
        'can_delete',
          v_actor.role = 'admin'
          or (
            comment.author_user_id = v_actor.auth_user_id
            and comment.created_at >= v_now - interval '5 minutes'
          ),
        'can_moderate', v_actor.role = 'admin' and comment.moderation_status = 'pending',
        'delete_deadline', comment.created_at + interval '5 minutes'
      ) as event
    from public.live_feed_comments comment
    where comment.organization_id = v_actor.organization_id
      and comment.deleted_at is null
      and comment.created_at >= v_cutoff
      and coalesce(comment.published_at, comment.created_at) < coalesce(p_before, 'infinity'::timestamptz)
      and (
        comment.moderation_status = 'approved'
        or comment.author_user_id = v_actor.auth_user_id
        or v_actor.role = 'admin'
      )
  ), combined as (
    select * from sale_events
    union all
    select * from comment_events
  ), limited as (
    select * from combined
    order by event_at desc, event_id desc
    limit v_limit
  )
  select coalesce(jsonb_agg(event order by event_at desc, event_id desc), '[]'::jsonb)
  into v_events
  from limited;

  return jsonb_build_object(
    'ok', true,
    'organization_id', v_actor.organization_id,
    'retention_days', 30,
    'limit', v_limit,
    'moderation_required', true,
    'events', v_events
  );
end;
$$;

revoke all on function public.get_live_feed_v1(integer, timestamptz) from public, anon;
grant execute on function public.get_live_feed_v1(integer, timestamptz) to authenticated;

create or replace function public.moderate_live_feed_comment_v1(
  p_comment_id uuid,
  p_decision text,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private, auth
as $$
declare
  v_actor record;
  v_comment public.live_feed_comments%rowtype;
  v_now timestamptz := statement_timestamp();
  v_decision text := lower(btrim(coalesce(p_decision, '')));
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
  v_block_reason text;
begin
  select * into v_actor from private.live_feed_actor_context();

  if v_actor.role <> 'admin' then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  if p_comment_id is null then
    raise exception 'comment_id_required' using errcode = '22023';
  end if;
  if v_decision not in ('approve','reject') then
    raise exception 'comment_moderation_decision_invalid' using errcode = '22023';
  end if;
  if char_length(coalesce(v_reason, '')) < 3 then
    raise exception 'comment_moderation_reason_required' using errcode = '22023';
  end if;
  if char_length(v_reason) > 240 then
    raise exception 'comment_moderation_reason_too_long' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_comment_id::text, 20260904));

  select * into v_comment
  from public.live_feed_comments
  where id = p_comment_id
    and organization_id = v_actor.organization_id
  for update;

  if not found then
    raise exception 'comment_not_found' using errcode = 'P0002';
  end if;

  if v_decision = 'approve' and v_comment.moderation_status = 'approved' and v_comment.deleted_at is null then
    return jsonb_build_object(
      'ok', true,
      'idempotent', true,
      'decision', 'approved',
      'event', jsonb_build_object(
        'event_id', 'comment:' || v_comment.id::text,
        'event_type', 'comment',
        'comment_id', v_comment.id,
        'created_at', v_comment.published_at,
        'submitted_at', v_comment.created_at,
        'published_at', v_comment.published_at,
        'moderation_status', 'approved',
        'actor_user_id', v_comment.author_user_id,
        'actor_name', v_comment.author_display_name,
        'actor_role', v_comment.author_role,
        'message', v_comment.body,
        'secondary_messages', '[]'::jsonb,
        'scope', v_comment.scope,
        'is_own', v_comment.author_user_id = v_actor.auth_user_id,
        'can_delete', true,
        'can_moderate', false,
        'delete_deadline', v_comment.created_at + interval '5 minutes'
      )
    );
  end if;

  if v_comment.deleted_at is not null or v_comment.moderation_status = 'rejected' then
    raise exception 'comment_already_rejected_or_removed' using errcode = 'P0001';
  end if;
  if v_comment.moderation_status <> 'pending' then
    raise exception 'comment_not_pending_moderation' using errcode = 'P0001';
  end if;

  if v_decision = 'approve' then
    v_block_reason := private.live_feed_comment_prohibited_reason(v_comment.body);
    if v_block_reason is not null then
      raise exception 'customer_information_not_allowed:%', v_block_reason using errcode = '22023';
    end if;

    insert into private.live_feed_comment_moderation_events(
      comment_id,organization_id,decision,original_body,moderated_at,
      moderated_by_user_id,moderated_by_email,reason
    ) values (
      v_comment.id,v_comment.organization_id,'approved',v_comment.body,v_now,
      v_actor.auth_user_id,v_actor.email,v_reason
    );

    update public.live_feed_comments
    set moderation_status = 'approved',
        published_at = v_now,
        moderated_at = v_now,
        moderated_by_user_id = v_actor.auth_user_id,
        moderation_reason = v_reason
    where id = v_comment.id
    returning * into v_comment;

    return jsonb_build_object(
      'ok', true,
      'idempotent', false,
      'decision', 'approved',
      'event', jsonb_build_object(
        'event_id', 'comment:' || v_comment.id::text,
        'event_type', 'comment',
        'comment_id', v_comment.id,
        'created_at', v_comment.published_at,
        'submitted_at', v_comment.created_at,
        'published_at', v_comment.published_at,
        'moderation_status', 'approved',
        'actor_user_id', v_comment.author_user_id,
        'actor_name', v_comment.author_display_name,
        'actor_role', v_comment.author_role,
        'message', v_comment.body,
        'secondary_messages', '[]'::jsonb,
        'scope', v_comment.scope,
        'is_own', v_comment.author_user_id = v_actor.auth_user_id,
        'can_delete', true,
        'can_moderate', false,
        'delete_deadline', v_comment.created_at + interval '5 minutes'
      )
    );
  end if;

  insert into private.live_feed_comment_moderation_events(
    comment_id,organization_id,decision,original_body,moderated_at,
    moderated_by_user_id,moderated_by_email,reason
  ) values (
    v_comment.id,v_comment.organization_id,'rejected',v_comment.body,v_now,
    v_actor.auth_user_id,v_actor.email,v_reason
  );

  update public.live_feed_comments
  set body = '[Comment rejected]',
      moderation_status = 'rejected',
      published_at = null,
      moderated_at = v_now,
      moderated_by_user_id = v_actor.auth_user_id,
      moderation_reason = v_reason,
      deleted_at = v_now,
      deleted_by_user_id = v_actor.auth_user_id,
      deletion_reason = 'admin_rejected:' || v_reason
  where id = v_comment.id;

  return jsonb_build_object(
    'ok', true,
    'idempotent', false,
    'decision', 'rejected',
    'comment_id', v_comment.id,
    'deleted_at', v_now
  );
end;
$$;

revoke all on function public.moderate_live_feed_comment_v1(uuid, text, text) from public, anon;
grant execute on function public.moderate_live_feed_comment_v1(uuid, text, text) to authenticated;

create or replace function private.prevent_live_feed_comment_moderation_audit_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  raise exception 'live_feed_comment_moderation_audit_is_immutable' using errcode = '42501';
end;
$$;

revoke all on function private.prevent_live_feed_comment_moderation_audit_change() from public, anon, authenticated;

drop trigger if exists live_feed_comment_moderation_events_immutable on private.live_feed_comment_moderation_events;
create trigger live_feed_comment_moderation_events_immutable
before update or delete on private.live_feed_comment_moderation_events
for each row execute function private.prevent_live_feed_comment_moderation_audit_change();

comment on function public.post_live_feed_comment_v1(text, uuid) is
  'Submits one free-form comment into fail-closed Admin moderation. Pending text is visible only to its author and organization Admins.';
comment on function public.get_live_feed_v1(integer, timestamptz) is
  'Returns verified sales, approved comments, and caller-authorized pending moderation rows from the last 30 days.';
comment on function public.moderate_live_feed_comment_v1(uuid, text, text) is
  'Organization-scoped Admin approval or rejection. Approval is the only transition that publishes free-form text to all members and Realtime.';
