create table if not exists public.user_display_name_changes (
  id bigint generated by default as identity primary key,
  changed_at timestamptz not null default now(),
  changed_by uuid not null,
  changed_by_email text not null,
  target_user_id uuid not null,
  target_email text not null,
  previous_display_name text not null,
  new_display_name text not null,
  auth_metadata_synced boolean,
  auth_metadata_error text,
  propagated_updates jsonb not null default '{}'::jsonb
);

create index if not exists user_display_name_changes_target_idx
  on public.user_display_name_changes (target_email, changed_at desc);

alter table public.user_display_name_changes enable row level security;

create or replace function public.admin_rename_app_user(
  p_target_email text,
  p_new_display_name text,
  p_changed_by uuid,
  p_changed_by_email text,
  p_target_user_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target_email text := lower(trim(p_target_email));
  v_new_name text := regexp_replace(trim(p_new_display_name), '[[:space:]]+', ' ', 'g');
  v_old_name text;
  v_role text;
  v_first_name text;
  v_last_name text;
  v_old_prefix text;
  v_audit_id bigint;
  v_assigned_manager_count integer := 0;
  v_assigned_admin_count integer := 0;
  v_profile_count integer := 0;
  v_feed_count integer := 0;
  v_rep_control_count integer := 0;
  v_manager_reference_count integer := 0;
  v_manager_control_count integer := 0;
begin
  if v_target_email = '' then raise exception 'email_required'; end if;
  if char_length(v_new_name) < 2 then raise exception 'display_name_too_short'; end if;
  if char_length(v_new_name) > 120 then raise exception 'display_name_too_long'; end if;
  if v_new_name ~ '[[:cntrl:]]' then raise exception 'display_name_contains_control_characters'; end if;

  select display_name, role into v_old_name, v_role
  from public.app_user_access
  where lower(email) = v_target_email and active = true
  for update;

  if not found then raise exception 'user_not_found'; end if;
  v_old_name := coalesce(nullif(trim(v_old_name), ''), v_target_email);
  if v_old_name = v_new_name then
    return jsonb_build_object('changed', false, 'display_name', v_new_name);
  end if;

  v_first_name := split_part(v_new_name, ' ', 1);
  v_last_name := nullif(regexp_replace(v_new_name, '^[^[:space:]]+[[:space:]]*', ''), '');
  v_old_prefix := '🎉 ' || v_old_name;

  update public.app_user_access set display_name = v_new_name where lower(email) = v_target_email;

  update public.users set first_name = v_first_name, last_name = v_last_name
  where id = p_target_user_id or auth_user_id = p_target_user_id or lower(coalesce(email, '')) = v_target_email;
  get diagnostics v_profile_count = row_count;

  update public.app_user_access set assigned_manager_name = v_new_name
  where lower(coalesce(assigned_manager_email, '')) = v_target_email;
  get diagnostics v_assigned_manager_count = row_count;

  update public.app_user_access set assigned_admin_name = v_new_name
  where lower(coalesce(assigned_admin_email, '')) = v_target_email;
  get diagnostics v_assigned_admin_count = row_count;

  update public.rep_override_controls set rep_display_name = v_new_name
  where lower(rep_email) = v_target_email;
  get diagnostics v_rep_control_count = row_count;

  update public.rep_override_controls set manager_name = v_new_name
  where lower(coalesce(manager_email, '')) = v_target_email;
  get diagnostics v_manager_reference_count = row_count;

  if not exists (select 1 from public.manager_override_controls where manager_name = v_new_name) then
    update public.manager_override_controls set manager_name = v_new_name
    where lower(coalesce(manager_email, '')) = v_target_email
       or (manager_email is null and manager_name = v_old_name);
    get diagnostics v_manager_control_count = row_count;
  elsif exists (
    select 1 from public.manager_override_controls
    where manager_name = v_new_name and lower(coalesce(manager_email, '')) = v_target_email
  ) then
    delete from public.manager_override_controls
    where manager_name <> v_new_name and lower(coalesce(manager_email, '')) = v_target_email;
    get diagnostics v_manager_control_count = row_count;
  end if;

  update public.sales_feed
  set rep_name = v_new_name,
      message = case
        when left(message, char_length(v_old_prefix)) = v_old_prefix
          then '🎉 ' || v_new_name || substring(message from char_length(v_old_prefix) + 1)
        else message
      end
  where rep_user_id = p_target_user_id;
  get diagnostics v_feed_count = row_count;

  insert into public.user_display_name_changes (
    changed_by, changed_by_email, target_user_id, target_email,
    previous_display_name, new_display_name, propagated_updates
  ) values (
    p_changed_by, lower(trim(p_changed_by_email)), p_target_user_id, v_target_email,
    v_old_name, v_new_name,
    jsonb_build_object(
      'profiles', v_profile_count,
      'assigned_manager_names', v_assigned_manager_count,
      'assigned_admin_names', v_assigned_admin_count,
      'sales_feed_rows', v_feed_count,
      'rep_override_controls', v_rep_control_count,
      'manager_references', v_manager_reference_count,
      'manager_override_controls', v_manager_control_count,
      'historical_sales_records_changed', false
    )
  ) returning id into v_audit_id;

  return jsonb_build_object(
    'changed', true,
    'audit_id', v_audit_id,
    'previous_display_name', v_old_name,
    'display_name', v_new_name
  );
end;
$$;

revoke all on function public.admin_rename_app_user(text,text,uuid,text,uuid) from public, anon, authenticated;
grant execute on function public.admin_rename_app_user(text,text,uuid,text,uuid) to service_role;
